"""Si(001) carrying a half-torus surface feature: a ring TRENCH or a ring RIDGE on ONE continuous
diamond lattice (docs/05 section 4.2 "patterned features"; the shape is the FIXED shared definition
``reflection_holo.structure.shapes.HalfTorus``, used unchanged).

Construction (DERIVED_HERE; frame of reflection_holo.geometry.frames, x = outward normal [001],
z = beam azimuth, y = z x x). The crystal origin sits at the slab origin, so the (001) atomic layer l
lies at x = l a/4 and is crystal layer n3 = l. The flat slab holds layers 0 .. l_s (``depth_layers``
= l_s + 1 layers; the bottom layer at x = 0, the flat top layer at x_surface = l_s a/4) inside the
periodic (y, z) window [0, L_y) x [0, L_z). With x_rel = x - x_surface:

* trench: the sites of the slab with ``feature.contains(x_rel, y, z)`` are REMOVED;
* ridge:  the sites of the SAME lattice (same origin, same basis, generated by the same
          ``lattice.diamond_sites_quarter`` call) above the slab with ``contains`` are ADDED.

No site is moved, so every atom is a site of the one lattice by construction; this is asserted.

Assertions run inside the builder by :func:`verify_feature_structure` (each is also exposed as a
function and tested; every tolerance is stated here and recorded in the metadata):

(a) every atom on a site of the single diamond lattice (``checks.assert_on_lattice_sites``,
    POSITION_TOL_A), and every atom obeys the feature rule at its own site;
(b) half-open periodic window in y and z, no duplicates under the periodic boundaries, and the atom
    count equals the analytic flat-slab count minus (trench) or plus (ridge) the number of feature
    sites found by an INDEPENDENT enumeration over the ring's bounding box. Together with (a) this
    makes the built set equal to the ideal set (a subset of equal size). y and z are periodic, so
    the ring must fit inside the cell with the stated margin ``ring_margin_A`` >= one in-plane
    period (the ring and its periodic images are then at least two periods apart);
(c) minimum interatomic distance equals the bulk nearest-neighbour distance a sqrt(3)/4 within
    POSITION_TOL_A; atoms below the lowest top layer are 4-coordinated; no atom is isolated and
    every added ridge atom is bonded to the layer below;
(d) the removed (trench) or added (ridge) count N matches the half-torus volume times the atom
    density, n V = (8/a^3) pi^2 R r^2, within the tolerance n (a/8) S, where S = 2 pi^2 R r
    (curved half surface) + 4 pi R r (flat annulus at x_rel = 0) is the surface of the half torus:
    the atoms in a shell of half the (001) layer spacing around the whole surface, i.e. a relative
    tolerance (a/8) S/V set by the surface-to-volume ratio. The dominant discretisation is the
    layering along the normal: the flat face x_rel = 0 is itself a layer, included in the trench and
    excluded from the ridge, a bias of +-n (a/8) 4 pi R r that is recorded (DERIVED_HERE, a stated
    order-of-magnitude bound, not a rigorous lattice-point bound);
(e) the top-layer height map computed from the BUILT atoms on a (y, z) grid equals
    ``HalfTorus.layer_height_A(y, z, layer_spacing_A=a/4)`` at every grid point more than one
    in-layer lattice spacing a/sqrt(2) from the ring boundary. The height map: for each layer, the
    layer is present at a grid point if the layer's lattice site nearest to the point (in y, z) is
    a built atom; the top layer is the highest present layer (a Voronoi tessellation of each
    layer). The ring boundary is the set of circles where ``layer_height_A`` jumps (the rims and
    every a/4 terrace edge of the ring). The nearest site is within the covering radius a/2 of the
    layer net, so equality is exact beyond a/2; a/sqrt(2) > a/2 is used. The fraction of grid points
    that disagree within the excluded band is recorded (reported, not asserted);
(f) the feature lies fully inside the cell: the ring with its margin inside the periodic window, the
    deepest removed layer at least MIN_LAYERS_BELOW_FEATURE layers above the slab bottom, the
    highest added layer below the top of the box; measured on the feature sites;
(g) the frame (``checks.assert_frame``).

Options (labels in metadata["options"]): bulk termination (ASSUMPTION B3), no 2x1 dimer
reconstruction (NOT IMPLEMENTED), no overlayer (ASSUMPTION B7), no relaxation of the feature walls
(ASSUMPTION). The feature geometry is PROJECT_INPUT item 13: the HalfTorus must carry its label and
source (a demo value is a registered stand-in, e.g. "ASSUMPTION B33"/"B34").
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass

import numpy as np

import reflection_holo
from reflection_holo.geometry.frames import SurfaceFrame, surface_frame
from reflection_holo.io.labels import require_evidence_label

from . import checks
from .checks import POSITION_TOL_A, WINDOW_TOL_A, StructureAssertionError
from .lattice import diamond_sites_quarter, nearest_neighbour_distance_A
from .shapes import HalfTorus
from .si001 import _AZIMUTHS

NORMAL_HKL = (0, 0, 1)
LABEL_PREFIXES = ("PROJECT_INPUT", "TEST_ONLY", "ASSUMPTION")
MIN_LAYERS_BELOW_FEATURE = 4      # intact (001) layers kept below the deepest removed layer
PERIOD_TOL_A = 1e-6               # extents must be integer numbers of in-plane periods
HEIGHT_MAP_GRID_A = 0.25          # sampling of the (e) height-map grid (numerical choice)
HEIGHT_MAP_PAD_A = 8.0            # grid extends this far beyond the ring's outer radius
_CHUNK_Z_A = 120.0                # generation chunk along z (memory only; no effect on the result)
_KEY_OFF = 1 << 20                # integer-key encoding of a/4 site coordinates


@dataclass
class Si001FeatureStructure:
    """Result of :func:`build_si001_with_feature` (field names shared with Si001Structure where the
    meaning is the same, so forward.cell.build_reflection_cell accepts it)."""
    positions_A: np.ndarray            # (N, 3) slab frame, angstrom
    species: np.ndarray                # (N,) "Si"
    Z: np.ndarray                      # (N,) 14
    cell_A: np.ndarray                 # (3, 3) rows = cell vectors (slab frame)
    pbc: tuple[bool, bool, bool]       # (x, y, z) = (False, True, True)
    frame: SurfaceFrame
    layer_index: np.ndarray            # (N,) (001) layer l, x = l a/4
    crystal_origin_slab_A: np.ndarray  # (3,) = 0: crystal origin at the slab origin
    feature: HalfTorus | None          # None for the flat reference
    feature_sites_A: np.ndarray        # removed (trench) or added (ridge) sites, (M, 3) slab frame
    request: dict                      # the builder arguments needed to re-verify the structure
    metadata: dict

    @property
    def n_atoms(self) -> int:
        return int(self.positions_A.shape[0])

    @property
    def periodic_lengths_A(self):
        return [None, float(self.cell_A[1, 1]), float(self.cell_A[2, 2])]


# --------------------------------------------------------------------------------------------------
# Geometry helpers
# --------------------------------------------------------------------------------------------------
def _family(az) -> str:
    fam = next((f for f, s in _AZIMUTHS.items() if az in s), None)
    if fam is None:
        raise ValueError(f"azimuth {az}: PROJECT_INPUT item 8 allows only the [110] or [100] "
                         f"families for Si(001)")
    return fam


def _in_plane(a_A: float, family: str) -> tuple[float, int]:
    """(period p along y and z, atoms per (001) layer per p x p cell)."""
    return (a_A / np.sqrt(2.0), 1) if family == "<110>" else (a_A, 2)


def _n_periods(extent_A, p, name) -> int:
    e = float(extent_A)
    if not (np.isfinite(e) and e > 0):
        raise ValueError(f"{name} must be finite and > 0")
    m = int(round(e / p))
    if m < 1 or abs(e - m * p) > PERIOD_TOL_A:
        raise ValueError(f"{name} = {e!r} A is not an integer number of in-plane lattice periods "
                         f"p = {p:.9f} A (the cell must be periodic); nearest allowed values "
                         f"{max(m, 1) * p:.9f} or {(max(m, 1) + 1) * p:.9f} A")
    return m


def feature_layer_counts(feature: HalfTorus, q_A: float) -> int:
    """Largest number of a/4 layers the feature can change: ceil(r/q) - 1 (layers n = 1..N added for
    the ridge, layers n = 0..-(N) i.e. N + 1 layers for the trench; shapes.py rule)."""
    return int(np.ceil(feature.minor_radius_A / q_A)) - 1


def _ring_box(feature: HalfTorus):
    Ro = feature.major_radius_A + feature.minor_radius_A
    return (feature.center_y_A - Ro, feature.center_y_A + Ro,
            feature.center_z_A - Ro, feature.center_z_A + Ro)


def _sites_in_box(frame: SurfaceFrame, a_A: float, lo_slab, hi_slab):
    """Integer a/4 crystal coordinates and slab positions of the ONE lattice (origin at the slab
    origin) covering the slab box [lo, hi] (with the one-cell margin of diamond_sites_quarter)."""
    lo, hi = np.asarray(lo_slab, float), np.asarray(hi_slab, float)
    corners = np.array([[x, y, z] for x in (lo[0], hi[0]) for y in (lo[1], hi[1])
                        for z in (lo[2], hi[2])])
    cc = frame.to_crystal(corners)
    n = diamond_sites_quarter(cc.min(axis=0), cc.max(axis=0), a_A)
    return n, frame.to_slab(n.astype(float) * (a_A / 4.0))


def _keys(n: np.ndarray) -> np.ndarray:
    n = np.asarray(n, np.int64) + _KEY_OFF
    if n.min() < 0 or n.max() >= 2 * _KEY_OFF:
        raise ValueError("site coordinates exceed the key range")
    return (n[:, 0] << 42) | (n[:, 1] << 21) | n[:, 2]


def _quarter_coords(pos_slab, frame, a_A):
    """Integer a/4 crystal coordinates of slab positions (after assertion (a) they are exact)."""
    return np.rint(frame.to_crystal(np.asarray(pos_slab, float)) / (a_A / 4.0)).astype(np.int64)


# --------------------------------------------------------------------------------------------------
# Assertions (each raises StructureAssertionError; tested one by one)
# --------------------------------------------------------------------------------------------------
def assert_ring_fits(feature: HalfTorus, L_y: float, L_z: float, margin_A: float,
                     min_margin_A: float) -> dict:
    """(b)/(f) the ring (outer radius R + r) fits inside the periodic window with the margin."""
    if not (np.isfinite(margin_A) and margin_A >= min_margin_A):
        raise StructureAssertionError(
            f"(b) ring_margin_A = {margin_A!r} A is below the stated minimum {min_margin_A:.6f} A "
            f"(one in-plane period): y and z are periodic, the ring must stay clear of its images")
    y0, y1, z0, z1 = _ring_box(feature)
    gaps = dict(y_low=y0, y_high=L_y - y1, z_low=z0, z_high=L_z - z1)
    bad = {k: v for k, v in gaps.items() if v < margin_A}
    if bad:
        raise StructureAssertionError(
            f"(f) the ring (centre ({feature.center_y_A}, {feature.center_z_A}) A, outer radius "
            f"{feature.major_radius_A + feature.minor_radius_A} A) does not fit inside the "
            f"periodic cell {L_y:.4f} x {L_z:.4f} A with the margin {margin_A} A: gaps {bad}")
    return dict(gaps_A=gaps, margin_A=float(margin_A), min_margin_A=float(min_margin_A),
                image_separation_A=float(min(L_y, L_z) - 2 * (feature.major_radius_A
                                                               + feature.minor_radius_A)))


def assert_feature_rule(positions_A, layer, feature: HalfTorus | None, l_s: int,
                        q_A: float) -> None:
    """(a) every atom obeys the feature rule at its own site: slab sites (l <= l_s) not removed,
    ridge sites (l > l_s) inside the half torus."""
    pos = np.asarray(positions_A, float)
    layer = np.asarray(layer)
    if np.any(layer < 0):
        raise StructureAssertionError("(a) atom below the slab bottom layer")
    if feature is None:
        if np.any(layer > l_s):
            raise StructureAssertionError("(a) flat reference: atom above the flat top layer")
        return
    x_rel = (layer - l_s) * q_A
    inside = feature.contains(x_rel, pos[:, 1], pos[:, 2])
    base = layer <= l_s
    if feature.kind == "trench":
        bad = ~base | inside
    else:
        bad = ~base & ~inside
    if np.any(bad):
        i = int(np.nonzero(bad)[0][0])
        raise StructureAssertionError(
            f"(a) {int(bad.sum())} atom(s) violate the {feature.kind} rule at their site; atom {i} "
            f"at {pos[i].tolist()} (layer {int(layer[i])})")


def feature_count_expectation(feature: HalfTorus, a_A: float) -> dict:
    """(d) n V, the tolerance n (a/8) S and the recorded flat-face bias (module docstring)."""
    R, r = feature.major_radius_A, feature.minor_radius_A
    n = 8.0 / a_A ** 3
    V = np.pi ** 2 * R * r ** 2
    S_curved = 2.0 * np.pi ** 2 * R * r
    S_flat = 4.0 * np.pi * R * r
    shell = a_A / 8.0
    tol = n * shell * (S_curved + S_flat)
    bias = n * shell * S_flat * (1.0 if feature.kind == "trench" else -1.0)
    return dict(atom_density_per_A3=n, half_volume_A3=V, expected_count=n * V,
                surface_curved_A2=S_curved, surface_flat_A2=S_flat, shell_A=shell,
                tolerance_count=tol, relative_tolerance=tol / (n * V),
                flat_face_bias_count=bias,
                rule="|N - n V| <= n (a/8) (S_curved + S_flat); DERIVED_HERE order-of-magnitude "
                     "bound set by the surface-to-volume ratio (module docstring (d))")


def assert_feature_count(n_feature: int, feature: HalfTorus, a_A: float) -> dict:
    e = feature_count_expectation(feature, a_A)
    dev = float(n_feature) - e["expected_count"]
    if abs(dev) > e["tolerance_count"]:
        raise StructureAssertionError(
            f"(d) {feature.kind} changes {n_feature} atoms; half-torus volume x density = "
            f"{e['expected_count']:.1f}, deviation {dev:+.1f} exceeds the tolerance "
            f"{e['tolerance_count']:.1f} (n (a/8) S, relative {e['relative_tolerance']:.3f})")
    return dict(e, measured_count=int(n_feature), deviation=dev,
                deviation_after_flat_face_bias=dev - e["flat_face_bias_count"])


def contour_distance_A(feature: HalfTorus, q_A: float, y, z) -> np.ndarray:
    """In-plane distance from (y, z) to the ring boundary: the circles rho = R +- s_n where
    layer_height_A jumps (s_n = sqrt(r^2 - (n q)^2) for the layers the feature changes)."""
    N = feature_layer_counts(feature, q_A)
    ns = np.arange(1, N + 1) if feature.kind == "ridge" else np.arange(0, N + 1)
    s = np.sqrt(feature.minor_radius_A ** 2 - (ns * q_A) ** 2)
    d = np.hypot(np.asarray(y, float) - feature.center_y_A,
                 np.asarray(z, float) - feature.center_z_A) - feature.major_radius_A
    dist = np.full(np.shape(d), np.inf)
    for sv in s:
        dist = np.minimum(dist, np.minimum(np.abs(d - sv), np.abs(d + sv)))
    return dist


def top_layer_height_map(positions_A, frame: SurfaceFrame, a_A: float, l_s: int,
                         y_grid_A, z_grid_A, L_y: float, L_z: float,
                         layer_range: tuple[int, int]) -> np.ndarray:
    """Top-layer height relative to the flat top layer (A) on the (y, z) grid, from the BUILT
    atoms (module docstring (e)): per layer, the lattice site nearest to each grid point in (y, z)
    is looked up among the built atoms (periodic in y and z); the top layer is the highest present
    layer in ``layer_range`` (inclusive). Raises if no layer of the range is present somewhere."""
    from scipy.spatial import cKDTree

    q = a_A / 4.0
    Y, Zg = np.meshgrid(np.asarray(y_grid_A, float), np.asarray(z_grid_A, float), indexing="ij")
    P = np.column_stack([Y.ravel(), Zg.ravel()])
    lo_l, hi_l = int(layer_range[0]), int(layer_range[1])
    pos = np.asarray(positions_A, float)
    sel = (np.rint(pos[:, 0] / q) >= lo_l) & (np.rint(pos[:, 0] / q) <= hi_l)
    built = np.unique(_keys(_quarter_coords(pos[sel], frame, a_A)))
    pad = 2.0 * a_A
    n, rs = _sites_in_box(frame, a_A, [lo_l * q - q, P[:, 0].min() - pad, P[:, 1].min() - pad],
                          [hi_l * q + q, P[:, 0].max() + pad, P[:, 1].max() + pad])
    wrapped = rs.copy()
    wrapped[:, 1] = np.mod(wrapped[:, 1], L_y)
    wrapped[:, 2] = np.mod(wrapped[:, 2], L_z)
    for ax, L in ((1, L_y), (2, L_z)):              # snap images of the window edge onto 0
        wrapped[np.abs(wrapped[:, ax] - L) < WINDOW_TOL_A, ax] = 0.0
    present_all = np.isin(_keys(_quarter_coords(wrapped, frame, a_A)), built)
    top = np.full(P.shape[0], np.iinfo(np.int64).min, dtype=np.int64)
    for l in range(lo_l, hi_l + 1):
        m = n[:, 2] == l
        if not np.any(m):
            continue
        tree = cKDTree(rs[m][:, 1:])
        _, idx = tree.query(P)
        top = np.where(present_all[m][idx], l, top)
    if np.any(top == np.iinfo(np.int64).min):
        raise StructureAssertionError(f"(e) no layer in {layer_range} is present at "
                                      f"{int(np.sum(top == np.iinfo(np.int64).min))} grid points")
    return ((top - l_s) * q).reshape(Y.shape)


def height_map_grid(feature: HalfTorus, L_y: float, L_z: float, step_A: float):
    """(y, z) grid over the ring's bounding box plus HEIGHT_MAP_PAD_A, clipped to the window."""
    y0, y1, z0, z1 = _ring_box(feature)
    ys = np.arange(max(0.0, y0 - HEIGHT_MAP_PAD_A), min(L_y, y1 + HEIGHT_MAP_PAD_A), step_A)
    zs = np.arange(max(0.0, z0 - HEIGHT_MAP_PAD_A), min(L_z, z1 + HEIGHT_MAP_PAD_A), step_A)
    return ys, zs


def assert_height_map(positions_A, frame: SurfaceFrame, a_A: float, l_s: int,
                      feature: HalfTorus, L_y: float, L_z: float, step_A: float) -> dict:
    """(e) height map from the built atoms equals layer_height_A beyond one in-layer lattice
    spacing a/sqrt(2) from the ring boundary; returns the statistics."""
    q = a_A / 4.0
    N = feature_layer_counts(feature, q)
    ys, zs = height_map_grid(feature, L_y, L_z, step_A)
    rng = (l_s - N - 2, l_s + N + 1)
    h = top_layer_height_map(positions_A, frame, a_A, l_s, ys, zs, L_y, L_z, rng)
    Y, Zg = np.meshgrid(ys, zs, indexing="ij")
    ideal = feature.layer_height_A(Y, Zg, layer_spacing_A=q)
    dist = contour_distance_A(feature, q, Y, Zg)
    spacing = a_A / np.sqrt(2.0)
    far = dist > spacing
    mism = np.abs(h - ideal) > POSITION_TOL_A
    bad = far & mism
    if np.any(bad):
        i = np.unravel_index(int(np.argmax(bad)), bad.shape)
        raise StructureAssertionError(
            f"(e) the top-layer height map of the built atoms differs from layer_height_A at "
            f"{int(bad.sum())} grid point(s) more than {spacing:.4f} A from the ring boundary; "
            f"first at (y, z) = ({Y[i]:.3f}, {Zg[i]:.3f}) A: built {h[i]:+.5f} A, ideal "
            f"{ideal[i]:+.5f} A")
    near = ~far
    footprint = feature.half_thickness_A(Y, Zg) > 0
    return dict(grid_step_A=float(step_A), n_points=int(h.size), n_checked=int(far.sum()),
                n_checked_inside_ring=int((far & footprint).sum()),
                n_near_boundary=int(near.sum()),
                n_disagree_near_boundary=int((near & mism).sum()),
                fraction_disagree_near_boundary=float((near & mism).sum() / max(near.sum(), 1)),
                fraction_disagree_inside_ring_footprint=float(
                    (footprint & mism).sum() / max(footprint.sum(), 1)),
                exclusion_distance_A=float(spacing),
                exclusion_rule="grid points within a/sqrt(2) of any circle where layer_height_A "
                               "jumps (rims and every a/4 terrace edge of the ring) are excluded",
                built_top_range_A=[float(h.min()), float(h.max())],
                ideal_top_range_A=[float(ideal.min()), float(ideal.max())])


def assert_feature_inside(feature_sites_A, feature: HalfTorus, l_s: int, q_A: float,
                          L: np.ndarray, margin_A: float) -> dict:
    """(f) measured on the feature sites: inside the ring's bounding box, clear of the periodic
    edges by the margin, deepest removed layer >= MIN_LAYERS_BELOW_FEATURE, ridge top below the box
    top."""
    fs = np.asarray(feature_sites_A, float)
    if fs.shape[0] == 0:
        raise StructureAssertionError("(f) the feature changes no lattice site")
    y0, y1, z0, z1 = _ring_box(feature)
    t = POSITION_TOL_A
    if (fs[:, 1].min() < y0 - t or fs[:, 1].max() > y1 + t or fs[:, 2].min() < z0 - t
            or fs[:, 2].max() > z1 + t):
        raise StructureAssertionError("(f) feature sites outside the ring's bounding box")
    if (fs[:, 1].min() < margin_A or fs[:, 1].max() > L[1] - margin_A
            or fs[:, 2].min() < margin_A or fs[:, 2].max() > L[2] - margin_A):
        raise StructureAssertionError("(f) feature sites closer than the margin to a periodic edge")
    lay = np.rint(fs[:, 0] / q_A).astype(np.int64)
    out = dict(feature_site_layers=[int(lay.min()), int(lay.max())],
               feature_site_y_range_A=[float(fs[:, 1].min()), float(fs[:, 1].max())],
               feature_site_z_range_A=[float(fs[:, 2].min()), float(fs[:, 2].max())])
    if feature.kind == "trench":
        if lay.min() < MIN_LAYERS_BELOW_FEATURE or lay.max() > l_s:
            raise StructureAssertionError(
                f"(f) trench removes layers {lay.min()}..{lay.max()}: it must stay within the slab "
                f"with at least {MIN_LAYERS_BELOW_FEATURE} intact layers below (0..{l_s})")
        out["intact_layers_below_trench"] = int(lay.min())
    else:
        if lay.min() <= l_s or (lay.max() + 1) * q_A > L[0]:
            raise StructureAssertionError("(f) ridge sites must lie above the flat top layer and "
                                          "below the top of the box")
        out["box_top_clearance_A"] = float(L[0] - lay.max() * q_A)
    return out


# --------------------------------------------------------------------------------------------------
# Verification of a built (or corrupted) structure
# --------------------------------------------------------------------------------------------------
def _flat_count(req: dict) -> int:
    return int(req["atoms_per_layer_per_cell"] * req["periods_y"] * req["periods_z"]
               * req["depth_layers"])


def independent_feature_site_count(feature: HalfTorus, frame: SurfaceFrame, a_A: float,
                                   l_s: int) -> int:
    """Number of lattice sites the feature changes, from a SEPARATE enumeration over the ring's
    bounding box only (not the chunked cell generation)."""
    q = a_A / 4.0
    N = feature_layer_counts(feature, q)
    y0, y1, z0, z1 = _ring_box(feature)
    lo_l, hi_l = (l_s - N - 1, l_s) if feature.kind == "trench" else (l_s + 1, l_s + N + 1)
    n, rs = _sites_in_box(frame, a_A, [lo_l * q, y0 - 1.0, z0 - 1.0],
                          [hi_l * q, y1 + 1.0, z1 + 1.0])
    lay = n[:, 2]
    m = (lay >= lo_l) & (lay <= hi_l)
    x_rel = (lay[m] - l_s) * q
    return int(np.count_nonzero(feature.contains(x_rel, rs[m, 1], rs[m, 2])))


def verify_feature_structure(s: Si001FeatureStructure) -> dict:
    """Run assertions (a) to (g) on the atoms of ``s`` (everything recomputed from the positions
    and the request; the stored layer index is not trusted). Returns the records; raises
    StructureAssertionError on the first failure."""
    req = s.request
    a, q = req["a_A"], req["a_A"] / 4.0
    l_s = req["depth_layers"] - 1
    L = np.diag(np.asarray(s.cell_A, float))
    per = [None, float(L[1]), float(L[2])]
    pos = np.asarray(s.positions_A, float)
    feat = s.feature
    rec, passed = {}, []

    checks.assert_frame(s.frame, NORMAL_HKL)                                        # (g)
    passed.append("(g) frame right-handed, x = outward normal [001], beam azimuth in the surface")

    checks.assert_on_lattice_sites(pos, s.frame, s.crystal_origin_slab_A, a)        # (a)
    layer = _quarter_coords(pos, s.frame, a)[:, 2]
    assert_feature_rule(pos, layer, feat, l_s, q)
    passed.append("(a) every atom on a site of one bulk diamond lattice and obeying the feature "
                  "rule at its site")

    if feat is not None:                                                            # (b) margin
        rec["ring_fit"] = assert_ring_fits(feat, L[1], L[2], req["ring_margin_A"],
                                           req["min_ring_margin_A"])
    checks.assert_half_open_window(pos[:, 1], L[1], "y")                            # (b)
    checks.assert_half_open_window(pos[:, 2], L[2], "z")
    flat = _flat_count(req)
    if feat is None:
        n_feat_indep, expected = 0, flat
    else:
        n_feat_indep = independent_feature_site_count(feat, s.frame, a, l_s)
        expected = flat - n_feat_indep if feat.kind == "trench" else flat + n_feat_indep
    checks.assert_no_duplicates_and_count(pos, per, expected)
    rec["count"] = dict(flat_slab_count=flat, feature_sites_independent=n_feat_indep,
                        expected=expected, built=int(pos.shape[0]))
    passed.append("(b) half-open periodic window, no duplicates under the PBC, atom count = flat "
                  "slab -/+ independently enumerated feature sites"
                  + ("; ring inside the cell with the stated margin" if feat is not None else ""))

    floor = l_s
    if feat is not None and feat.kind == "trench" and len(s.feature_sites_A):
        floor = int(np.rint(np.asarray(s.feature_sites_A)[:, 0] / q).min()) - 1
    interior = (layer >= 1) & (layer <= floor - 1)
    i, j, _, _ = checks.assert_min_distance_and_coordination(pos, per, a, interior)  # (c)
    coord = np.bincount(i, minlength=pos.shape[0])
    if np.any(coord == 0):
        raise StructureAssertionError(f"(c) {int(np.sum(coord == 0))} isolated atom(s) (no "
                                      f"neighbour at a sqrt(3)/4)")
    if feat is not None and feat.kind == "ridge":
        added = layer > l_s
        below = np.zeros(pos.shape[0], bool)
        down = layer[j] == layer[i] - 1
        below[i[down]] = True
        if np.any(added & ~below):
            raise StructureAssertionError(f"(c) {int(np.sum(added & ~below))} ridge atom(s) not "
                                          f"bonded to the layer below")
    rec["coordination_histogram"] = {int(k): int(v) for k, v in
                                     zip(*np.unique(coord, return_counts=True))}
    passed.append("(c) minimum distance = a*sqrt(3)/4; interior atoms 4-coordinated; no isolated "
                  "atom" + ("; every ridge atom bonded to the layer below"
                            if feat is not None and feat.kind == "ridge" else ""))

    if feat is not None:
        n_feat = abs(int(pos.shape[0]) - flat)
        rec["volume_count"] = assert_feature_count(n_feat, feat, a)                  # (d)
        passed.append("(d) removed/added count = half-torus volume x atom density within "
                      "n (a/8) S")
        rec["height_map"] = assert_height_map(pos, s.frame, a, l_s, feat, L[1], L[2],
                                              req["height_map_grid_A"])              # (e)
        passed.append("(e) top-layer height map of the built atoms = layer_height_A (a/4) beyond "
                      "a/sqrt(2) from the ring boundary")
        rec["inside"] = assert_feature_inside(s.feature_sites_A, feat, l_s, q, L,
                                              req["ring_margin_A"])                  # (f)
        passed.append("(f) feature fully inside the cell")
    else:
        if np.max(layer) != l_s:
            raise StructureAssertionError("(e) flat reference: top layer is not l_s")
    rec["assertions_passed"] = passed
    return rec


# --------------------------------------------------------------------------------------------------
# Builder
# --------------------------------------------------------------------------------------------------
def _options() -> dict:
    return dict(
        termination=dict(value="bulk", label="ASSUMPTION B3",
                         note="unreconstructed bulk truncation, also on the feature walls"),
        dimer_reconstruction=dict(value="not enabled", status="NOT IMPLEMENTED: no Si(001)-(2x1) "
                                  "dimer geometry source has been read"),
        overlayer=dict(value=None, label="ASSUMPTION B7",
                       note="clean surface; the real surface is ion-milled (PROJECT_INPUT item 12)"),
        riser_relaxation=dict(value="none", label="ASSUMPTION",
                              note="no relaxation of the feature walls or terrace edges"),
    )


def _build(*, azimuth_uvw, azimuth_label, feature, extent_y_A, extent_z_A, depth_layers,
           lattice_parameter_A, lattice_label, ring_margin_A, vacuum_above_A):
    require_evidence_label(lattice_label, "lattice parameter (model_assumptions B2)",
                           accepted=LABEL_PREFIXES, qualified=True)
    a = float(lattice_parameter_A)
    if not (np.isfinite(a) and a > 0.0):
        raise ValueError(f"lattice_parameter_A must be finite and > 0, got {lattice_parameter_A!r}")
    q = a / 4.0
    require_evidence_label(azimuth_label, "azimuth (PROJECT_INPUT item 8)",
                           accepted=LABEL_PREFIXES, qualified=True)
    az = tuple(int(v) for v in azimuth_uvw)
    if not np.allclose(np.asarray(azimuth_uvw, float), az):
        raise ValueError("azimuth_uvw must be integer indices")
    frame = surface_frame(NORMAL_HKL, az)
    family = _family(az)
    checks.assert_frame(frame, NORMAL_HKL)
    if feature is not None:
        if not isinstance(feature, HalfTorus):
            raise TypeError("feature must be a reflection_holo.structure.shapes.HalfTorus")
        require_evidence_label(feature.label, "feature geometry (PROJECT_INPUT item 13)",
                               accepted=LABEL_PREFIXES, qualified=True)
    if isinstance(depth_layers, bool) or int(depth_layers) != depth_layers or depth_layers < 2:
        raise ValueError("depth_layers must be an integer >= 2")
    depth_layers = int(depth_layers)
    vac = float(vacuum_above_A)
    if not (np.isfinite(vac) and vac > 0.0):
        raise ValueError("vacuum_above_A must be finite and > 0")
    p, apl = _in_plane(a, family)
    my = _n_periods(extent_y_A, p, "extent_y_A")
    mz = _n_periods(extent_z_A, p, "extent_z_A")
    L = np.array([0.0, my * p, mz * p])
    l_s = depth_layers - 1
    x_s = l_s * q
    margin = float(ring_margin_A) if feature is not None else None

    N = 0
    if feature is not None:
        assert_ring_fits(feature, L[1], L[2], margin, p)                            # (b), (f)
        N = feature_layer_counts(feature, q)
        if feature.kind == "trench" and l_s - N < MIN_LAYERS_BELOW_FEATURE:
            raise ValueError(
                f"(f) depth_layers = {depth_layers} is too thin for a trench of minor radius "
                f"{feature.minor_radius_A} A ({N + 1} layers removed at most): need at least "
                f"{N + 1 + MIN_LAYERS_BELOW_FEATURE} layers")
    l_hi = l_s + (N if feature is not None and feature.kind == "ridge" else 0)

    # --- one continuous lattice, generated in chunks along z ---------------------------------
    tol = WINDOW_TOL_A
    parts, fparts, lparts = [], [], []
    n_chunks = max(1, int(np.ceil(L[2] / _CHUNK_Z_A)))
    edges = np.linspace(0.0, L[2], n_chunks + 1)
    for c in range(n_chunks):
        z0, z1 = edges[c], edges[c + 1]
        n, rs = _sites_in_box(frame, a, [-q, -p, z0 - p], [(l_hi + 1) * q, L[1] + p, z1 + p])
        layer = n[:, 2]
        win = ((rs[:, 1] >= -tol) & (rs[:, 1] < L[1] - tol) & (rs[:, 2] >= z0 - tol)
               & (rs[:, 2] < z1 - tol) & (layer >= 0) & (layer <= l_hi))
        n, rs, layer = n[win], rs[win], layer[win]
        base = layer <= l_s
        if feature is None:
            keep, fsite = base, np.zeros(len(layer), bool)
        else:
            inside = feature.contains((layer - l_s) * q, rs[:, 1], rs[:, 2])
            if feature.kind == "trench":
                fsite = base & inside
                keep = base & ~inside
            else:
                fsite = (layer > l_s) & inside
                keep = base | fsite
        parts.append(rs[keep])
        lparts.append(layer[keep])
        fparts.append(rs[fsite])
    rs = np.concatenate(parts)
    layer = np.concatenate(lparts)
    fs = np.concatenate(fparts) if fparts else np.zeros((0, 3))
    for arr in (rs, fs):
        arr[:, 1:][np.abs(arr[:, 1:]) < tol] = 0.0                  # snap boundary rows to 0
    order = np.lexsort((rs[:, 1], rs[:, 2], rs[:, 0]))
    rs, layer = rs[order], layer[order]
    fs = fs[np.lexsort((fs[:, 1], fs[:, 2], fs[:, 0]))] if len(fs) else fs
    L[0] = float(rs[:, 0].max()) + vac
    cell = np.diag(L)

    req = dict(a_A=a, depth_layers=depth_layers, periods_y=my, periods_z=mz,
               atoms_per_layer_per_cell=apl, ring_margin_A=margin, min_ring_margin_A=float(p),
               height_map_grid_A=HEIGHT_MAP_GRID_A, family=family)
    s = Si001FeatureStructure(positions_A=rs, species=np.full(rs.shape[0], "Si"),
                              Z=np.full(rs.shape[0], 14, dtype=np.int64), cell_A=cell,
                              pbc=(False, True, True), frame=frame, layer_index=layer,
                              crystal_origin_slab_A=np.zeros(3), feature=feature,
                              feature_sites_A=fs, request=req, metadata={})
    rec = verify_feature_structure(s)

    # --- metadata (keys shared with Si001Structure where forward.cell reads them) --------------
    pos_hash = hashlib.sha256(np.ascontiguousarray(rs, dtype="<f8").tobytes()).hexdigest()
    top_layers = np.array([x_s + v for v in (rec.get("height_map", {})
                                             .get("built_top_range_A", [0.0, 0.0]))])
    feature_md = None
    if feature is not None:
        feature_md = dict(
            shape="reflection_holo.structure.shapes.HalfTorus", kind=feature.kind,
            center_y_A=feature.center_y_A, center_z_A=feature.center_z_A,
            major_radius_A=feature.major_radius_A, minor_radius_A=feature.minor_radius_A,
            label=feature.label, source=feature.source, project_input="item 13",
            x_surface_A=x_s, flat_top_layer_index=l_s,
            n_removed=int(len(fs)) if feature.kind == "trench" else 0,
            n_added=int(len(fs)) if feature.kind == "ridge" else 0,
            max_layers_changed=N if feature.kind == "ridge" else N + 1,
            top_layer_x_range_A=[float(top_layers[0]), float(top_layers[1])],
            rule=("sites of the flat slab with contains(x - x_surface, y, z) removed"
                  if feature.kind == "trench" else
                  "sites of the same lattice above the flat top layer with contains(x - x_surface, "
                  "y, z) added"))
    s.metadata = dict(
        schema="reflection_holo.structure.features/1",
        builder=("reflection_holo.structure.features.build_si001_with_feature" if feature is not None
                 else "reflection_holo.structure.features.build_si001_flat_reference"),
        package_version=reflection_holo.__version__, units="angstrom",
        surface=dict(hkl=list(NORMAL_HKL), outward_normal="[001]",
                     label="PROJECT_INPUT item 11 (Si(001), supplied by Ali 2026-09-22)"),
        azimuth=dict(uvw=list(az), family=family, label=azimuth_label, project_input="item 8"),
        frame=dict(convention="x = outward normal, z = beam azimuth, y = z x x "
                              "(docs/physics_conventions.md)",
                   x_hat_crystal=frame.x_hat.tolist(), y_hat_crystal=frame.y_hat.tolist(),
                   z_hat_crystal=frame.z_hat.tolist(), crystal_origin_slab_A=[0.0, 0.0, 0.0]),
        lattice=dict(a_A=a, a_label=lattice_label, basis="constants.DIAMOND_BASIS (SM02)",
                     layer_spacing_A=q, nearest_neighbour_A=nearest_neighbour_distance_A(a),
                     in_plane_period_A=float(p), one_continuous_lattice=True),
        cell=dict(vectors_A=cell.tolist(), pbc=[False, True, True], vacuum_above_A=vac,
                  note="x is not periodic; bottom layer at x = 0; vacuum_above_A above the highest "
                       "atom; y and z are integer numbers of in-plane periods"),
        # compatibility with forward.cell.build_reflection_cell: ONE flat terrace (the surface that
        # carries the feature); the feature itself is NOT a terrace (see "feature")
        staircase=dict(kind="none: one flat terrace carrying a surface feature", edges=None,
                       staircase_axis="y", edge_axis="z", terrace_layers=[0],
                       terrace_widths_periods=[my], boundary_step_layers=0,
                       net_height_change_layers=0),
        terrace_map=[dict(index=0, s_range_A=[0.0, float(L[1])], width_periods=my,
                          top_layer_relative=0, top_layer_index=l_s, top_height_A=x_s,
                          n_atoms=int(rs.shape[0]),
                          note="the flat (001) surface; the feature's top-layer range is in "
                               "metadata['feature']")],
        steps=[],
        feature=feature_md,
        options=_options(),
        depth_layers=depth_layers, periods_y=my, periods_z=mz,
        atom_count=int(rs.shape[0]), expected_atom_count=rec["count"]["expected"],
        tolerances_A=dict(position=POSITION_TOL_A, window=WINDOW_TOL_A,
                          duplicate_distance=checks.DUPLICATE_DIST_A,
                          ring_margin_min=float(p), height_map_exclusion=a / np.sqrt(2.0),
                          count_shell=a / 8.0),
        checks={k: v for k, v in rec.items() if k != "assertions_passed"},
        assertions_passed=rec["assertions_passed"],
        positions_sha256=pos_hash,
    )
    return s


def build_si001_with_feature(*, azimuth_uvw, azimuth_label: str, feature: HalfTorus,
                             extent_y_A: float, extent_z_A: float, depth_layers: int,
                             lattice_parameter_A: float, lattice_label: str,
                             ring_margin_A: float, vacuum_above_A: float) -> Si001FeatureStructure:
    """Si(001) slab with a half-torus trench or ridge; assertions (a) to (g) run inside.

    Every argument is required (keyword-only, no defaults):

    azimuth_uvw, azimuth_label  beam azimuth (PROJECT_INPUT item 8; [110] or [100] families) and
                                its evidence label
    feature                     HalfTorus (PROJECT_INPUT item 13, carrying its label and source);
                                centre in the cell's (y, z) coordinates
    extent_y_A, extent_z_A      periodic cell lengths; each must be an integer number of in-plane
                                periods (a for <100>, a/sqrt(2) for <110>), else refused
    depth_layers                number of (001) layers of the flat slab (bottom layer at x = 0,
                                flat top layer at x_surface = (depth_layers - 1) a/4)
    lattice_parameter_A, lattice_label  the lattice parameter and its label (e.g. A_SI_A,
                                "ASSUMPTION B2")
    ring_margin_A               stated clearance between the ring's bounding box and the periodic
                                cell edges; must be >= one in-plane period
    vacuum_above_A              vacuum above the highest atom in the (non-periodic) x box
    """
    if feature is None:
        raise ValueError("feature is required (PROJECT_INPUT item 13); the flat reference is "
                         "build_si001_flat_reference")
    return _build(azimuth_uvw=azimuth_uvw, azimuth_label=azimuth_label, feature=feature,
                  extent_y_A=extent_y_A, extent_z_A=extent_z_A, depth_layers=depth_layers,
                  lattice_parameter_A=lattice_parameter_A, lattice_label=lattice_label,
                  ring_margin_A=ring_margin_A, vacuum_above_A=vacuum_above_A)


def build_si001_flat_reference(*, azimuth_uvw, azimuth_label: str, extent_y_A: float,
                               extent_z_A: float, depth_layers: int, lattice_parameter_A: float,
                               lattice_label: str, vacuum_above_A: float) -> Si001FeatureStructure:
    """The same slab WITHOUT the feature (same lattice, origin, window and layers), for the
    flat-surface reference run; assertions (a), (b), (c), (g) and a flat top layer."""
    return _build(azimuth_uvw=azimuth_uvw, azimuth_label=azimuth_label, feature=None,
                  extent_y_A=extent_y_A, extent_z_A=extent_z_A, depth_layers=depth_layers,
                  lattice_parameter_A=lattice_parameter_A, lattice_label=lattice_label,
                  ring_margin_A=None, vacuum_above_A=vacuum_above_A)
