#!/usr/bin/env python3
"""B5 -- independent verification of the L8 and L9 bibliography proposals and their merge.

Copied from tools/bib/b4_check.py (B4, 2026-09-23) and adapted; b4_check.py itself is unchanged.

Inputs: docs/agent_reports/L8_new_refs.bib, docs/agent_reports/L9_new_refs.bib (never edited),
tools/bib/b5_routes.yaml (extra routes and declared decisions), the committed record cache
docs/agent_reports/crossref_cache/ and the baseline references.bib at `baseline_rev`.

Subcommands (paths resolved from the repository root):

  fetch     for every proposed entry: GET https://api.crossref.org/works/<DOI> (no mailto parameter,
            no personal data; User-Agent "Holography-bibcheck/1.0"); on 404, GET https://doi.org/ra/<DOI>
            and, for JaLC DOIs, https://api.japanlinkcenter.org/dois/<DOI>, for DataCite DOIs
            https://api.datacite.org/dois/<DOI>.  arXiv ids: the arXiv query API and arXiv's OAI-PMH
            interface (metadataPrefix arXiv and arXivRaw).  Extra routes from b5_routes.yaml: CiNii
            Research record JSON, Europe PMC core record by DOI, the Crossref record of a second DOI named
            in a note, the J-STAGE landing page named in the Crossref record (citation_* meta tags), a
            Crossref bibliographic query for items without a DOI (logged, never used to add a DOI unless
            declared), and -- for web pages, slides, manufacturer and company documents without any
            registry record -- the page itself: HTTP status, final URL, SHA-256, the page's <title>/<h1>
            (HTML) or title metadata and page count (PDF), and whether each expected string (the entry's
            title and owner, declared in b5_routes.yaml) occurs in the page text.  Page text is NOT stored
            (facility pages and slides carry staff contacts); only the checks are cached, as
            docs/agent_reports/crossref_cache/<KEY>.page<N>.json.  Every response is indexed in
            _index.json with URL, HTTP status and fetch time.
  report    compare every proposal field by field with its record(s); detect duplicates against the
            baseline references.bib (same DOI, same arXiv id, same key, or same work = same first-author
            family name and title similarity >= 0.90) and between L8 and L9; check the bibliographic
            fields that the L8/L9 report texts print next to each DOI; check that every citation key
            used in docs/*.md and docs/source_map.tsv exists in references.bib; write
            docs/agent_reports/B5_results.tsv and the generated block of B5_verification_log.md.
  merge     rebuild docs/references.bib = baseline + the verified, deduplicated entries (fields copied
            from the records; for no-DOI items the proposal's fields as checked on the page).
            Idempotent: always starts from the baseline revision, and refuses to write if the current
            file carries edits other than B5's own.
  validate  crossref_check.py validate (balanced braces, unique keys, notes, doi shape, no doi in the
            UNVERIFIED section, every doi backed by a cached registry record -- Crossref, DataCite or JaLC).
"""
from __future__ import annotations

import argparse
import datetime as dt
import difflib
import hashlib
import html
import json
import re
import subprocess
import sys
import urllib.parse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import bibtools as bt  # noqa: E402
import crossref_check as cc  # noqa: E402

ROOT = cc.ROOT
BIB = cc.BIB
REPORTS = cc.REPORTS
CACHE = cc.CACHE
ROUTES = Path(__file__).resolve().parent / "b5_routes.yaml"
TSV = REPORTS / "B5_results.tsv"
LOG = REPORTS / "B5_verification_log.md"
SOURCES = {"L8": REPORTS / "L8_new_refs.bib", "L9": REPORTS / "L9_new_refs.bib"}
REPORT_MD = {"L8": REPORTS / "L8_oxide_plasma.md", "L9": REPORTS / "L9_microscope_detector.md"}
REPORT_OF = {"L8": "L8\\_oxide\\_plasma.md", "L9": "L9\\_microscope\\_detector.md"}
BIBFILE_OF = {"L8": "L8\\_new\\_refs.bib", "L9": "L9\\_new\\_refs.bib"}
DATE = "2026-09-24"
SECTION = "%% --- 4o. Records added by B5 (proposals of L8 and L9, each checked against its registry record or page) ---"
GEN_BEGIN = "<!-- BEGIN GENERATED BY tools/bib/b5_check.py report -->"
GEN_END = "<!-- END GENERATED -->"


def load_routes():
    import yaml
    return yaml.safe_load(ROUTES.read_text()) or {}


def proposals():
    """[(source, Entry)] in file order."""
    out = []
    for src, path in SOURCES.items():
        for e in bt.parse(path.read_text()):
            out.append((src, e))
    return out


def arxiv_id(e):
    return (e.get("eprint") or "").strip() or None


# ======================================================================= fetch
def jalc_url(doi):
    return "https://api.japanlinkcenter.org/dois/" + urllib.parse.quote(doi, safe="")


def cmd_fetch(args):
    routes = load_routes()
    idx = cc.load_index()
    want = set(args.keys)
    for src, e in proposals():
        k = e.key
        if want and k not in want:
            continue
        doi = e.get("doi")
        if doi:
            st, _ = cc.cached_get(f"{k}.json", cc.works_url(doi), idx, args.refresh)
            print(f"{src} {k}: Crossref /works {st}")
            if st == 404:
                st2, body = cc.cached_get(f"{k}.ra.json", "https://doi.org/ra/" + doi, idx, args.refresh)
                ra = json.loads(body)[0].get("RA") if st2 == 200 else None
                print(f"   doi.org/ra {st2}: {ra}")
                if ra == "JaLC":
                    st3, _ = cc.cached_get(f"{k}.jalc.json", jalc_url(doi), idx, args.refresh)
                    print(f"   JaLC {st3}")
                elif ra == "DataCite":
                    st3, _ = cc.cached_get(f"{k}.datacite.json",
                                           "https://api.datacite.org/dois/" + urllib.parse.quote(doi, safe=""),
                                           idx, args.refresh)
                    print(f"   DataCite {st3}")
        aid = arxiv_id(e)
        if aid:
            st, _ = cc.cached_get(f"{k}.arxiv.xml", "https://export.arxiv.org/api/query?id_list=" + aid, idx,
                                  args.refresh, accept="*/*")
            print(f"   arXiv query API {st}")
            for pfx in ("arXiv", "arXivRaw"):
                url = ("https://oaipmh.arxiv.org/oai?verb=GetRecord&identifier=oai:arXiv.org:" + aid
                       + "&metadataPrefix=" + pfx)
                st, _ = cc.cached_get(f"{k}.oai-{pfx.lower()}.xml", url, idx, args.refresh, accept="*/*")
                print(f"   arXiv OAI-PMH {pfx} {st}")
            am = arxiv_msg(k)
            x0 = (load_routes().get("extra") or {}).get(k) or {}
            if am and am["_doi"] and am["_doi"].lower() not in ((doi or "").lower(), (x0.get("claim_doi") or "").lower()):
                st, _ = cc.cached_get(f"{k}.arxivdoi.json", cc.works_url(am["_doi"]), idx, args.refresh)
                print(f"   Crossref /works of the DOI in the arXiv record {am['_doi']}: {st}")
        x = (routes.get("extra") or {}).get(k) or {}
        if x.get("cinii"):
            st, _ = cc.cached_get(f"{k}.cinii.json", f"https://cir.nii.ac.jp/crid/{x['cinii']}.json", idx,
                                  args.refresh)
            print(f"   CiNii {x['cinii']} {st}")
        if x.get("claim_doi"):
            st, _ = cc.cached_get(f"{k}.claim.json", cc.works_url(x["claim_doi"]), idx, args.refresh)
            print(f"   Crossref /works of the DOI claimed in the report {x['claim_doi']}: {st}")
        if x.get("alt_doi"):
            st, _ = cc.cached_get(f"{k}.altdoi.json", cc.works_url(x["alt_doi"]), idx, args.refresh)
            print(f"   Crossref /works of the second DOI named in the note {x['alt_doi']}: {st}")
        if x.get("europepmc") and doi:
            url = ("https://www.ebi.ac.uk/europepmc/webservices/rest/search?query="
                   + urllib.parse.quote(f'DOI:"{doi}"') + "&resultType=core&format=json")
            st, _ = cc.cached_get(f"{k}.epmc.json", url, idx, args.refresh)
            print(f"   Europe PMC core record by DOI {st}")
        if x.get("jstage"):
            jstage_fetch(k, idx, args.refresh)
        if x.get("crossref_query"):
            url = (cc.CROSSREF + "?query.bibliographic=" + urllib.parse.quote(x["crossref_query"])
                   + "&rows=5&select=DOI,title,author,container-title,issued,page,volume,type")
            st, _ = cc.cached_get(f"{k}.crquery.json", url, idx, args.refresh)
            print(f"   Crossref bibliographic query {st}")
        for i, pg in enumerate(x.get("page") or [], 1):
            st = page_fetch(k, i, pg, idx, args.refresh, e)
            print(f"   page {i} {pg['url']} -> {st}")
        if x.get("wp_rest"):
            st, _ = cc.cached_get(f"{k}.wprest.json", x["wp_rest"], idx, args.refresh)
            print(f"   WordPress REST record of the page {st}")
        for a in x.get("aux") or []:
            st, _ = cc.cached_get(f"{k}.{a['name']}.json", a["url"], idx, args.refresh,
                                  accept=a.get("accept", "application/json"))
            print(f"   {a['name']} {a['url']} -> {st}")
    return 0


# ======================================================================= page and J-STAGE routes
def http_get_full(url, accept="*/*", tries=3):
    """GET with redirects followed; returns (status, body, final_url, content_type)."""
    import time
    import urllib.error
    import urllib.request
    last = (None, b"", url, "")
    for n in range(tries):
        req = urllib.request.Request(url, headers={"User-Agent": cc.UA, "Accept": accept})
        try:
            with urllib.request.urlopen(req, timeout=90) as r:
                return r.status, r.read(), r.geturl(), r.headers.get("Content-Type", "")
        except urllib.error.HTTPError as exc:
            last = (exc.code, b"", url, exc.headers.get("Content-Type", "") if exc.headers else "")
            if exc.code not in (429, 500, 502, 503, 504):
                return last
        except Exception as exc:  # network error
            last = (None, str(exc).encode(), url, "")
        time.sleep(2 * (n + 1))
    return last


def html_text(body):
    t = body.decode("utf-8", "replace")
    t = re.sub(r"(?is)<(script|style|noscript)\b.*?</\1>", " ", t)
    title = _xml_tag(t, "title")
    h1 = [re.sub(r"<[^>]+>", " ", x) for x in re.findall(r"(?is)<h1\b[^>]*>(.*?)</h1>", t)]
    txt = html.unescape(re.sub(r"<[^>]+>", " ", t))
    return (re.sub(r"\s+", " ", txt).strip(), (title or [""])[0],
            [re.sub(r"\s+", " ", html.unescape(x)).strip() for x in h1])


def pdf_pages_text(body):
    """[(page number, text)] with pymupdf (else pypdf); plus metadata title / creation date and page count."""
    try:
        import pymupdf
        d = pymupdf.open(stream=body, filetype="pdf")
        meta = d.metadata or {}
        pages = [(i + 1, d[i].get_text()) for i in range(d.page_count)]
        return pages, {"pages": d.page_count, "title": meta.get("title") or "",
                       "subject": meta.get("subject") or "", "creationDate": meta.get("creationDate") or "", "extracted_with": "pymupdf"}
    except ImportError:
        import io
        import pypdf
        r = pypdf.PdfReader(io.BytesIO(body))
        m = r.metadata or {}
        return ([(i + 1, pg.extract_text() or "") for i, pg in enumerate(r.pages)],
                {"pages": len(r.pages), "title": m.get("/Title") or "", "creationDate": m.get("/CreationDate") or "",
                 "extracted_with": "pypdf"})


def norm_text(s):
    return re.sub(r"\s+", " ", bt.fold(s.replace("\u00ad", "").replace("-\n", ""))).strip()


def page_expectations(pg, e):
    """[(what, string)]: the declared strings plus, if flagged, the entry's title and author family names."""
    out = []
    if e is not None and pg.get("entry_title"):
        out.append(("entry title", bt.latex_to_unicode(e.get("title") or "").strip()))
    if e is not None and pg.get("authors"):
        for n in bt.split_names(e.get("author") or ""):
            out.append(("author family name", bt.parse_name(n)["family"]))
    return out + [(w, s) for w, s in (pg.get("expect") or [])]


def page_fetch(k, i, pg, idx, refresh=False, e=None):
    """Fetch one page/document of a no-DOI entry; cache only the checks (never the page text)."""
    name = f"{k}.page{i}.json"
    path = CACHE / name
    if path.exists() and not refresh and json.loads(path.read_text()).get("status") == 200:
        return 200
    st, body, final, ctype = http_get_full(pg["url"])
    rec = {"url": pg["url"], "final_url": final, "status": st, "content_type": ctype,
           "fetched_utc": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}
    if st == 200:
        rec["sha256"] = hashlib.sha256(body).hexdigest()
        rec["bytes"] = len(body)
        if body[:5] == b"%PDF-" or "pdf" in ctype.lower():
            pages, meta = pdf_pages_text(body)
            rec["pdf"] = meta
        else:
            txt, title, h1 = html_text(body)
            pages = [(1, txt)]
            rec["html_title"], rec["h1"] = re.sub(r"\s+", " ", html.unescape(title)).strip(), h1
        checks = []
        for what, s in page_expectations(pg, e):
            ns = norm_text(s)
            hit = [n for n, tx in pages if ns and ns in norm_text(tx)]
            checks.append({"what": what, "string": s, "found": bool(hit),
                           "on_pages": hit[:5] if rec.get("pdf") else None})
        rec["checks"] = checks
    path.write_text(json.dumps(rec, indent=1, ensure_ascii=False) + "\n")
    idx[name] = {"url": pg["url"], "status": st, "fetched_utc": rec["fetched_utc"],
                 "stored": str(path.relative_to(ROOT)), "note": "checks only; page text not stored"}
    cc.save_index(idx)
    return st


JSTAGE_META = ("citation_title", "citation_author", "citation_journal_title", "citation_volume", "citation_issue",
               "citation_firstpage", "citation_lastpage", "citation_publication_date", "citation_date", "citation_doi")


def jstage_fetch(k, idx, refresh=False):
    """J-STAGE landing page named in the Crossref record (resource.primary.URL), in its Japanese and English
    views; only the citation_* meta tags are cached (as <KEY>.jstage.json)."""
    name = f"{k}.jstage.json"
    path = CACHE / name
    if path.exists() and not refresh:
        return
    crm = crossref_msg(f"{k}.json")
    url = ((crm.get("resource") or {}).get("primary") or {}).get("URL", "")
    out = {"record_url": url, "views": []}
    for lang in ("ja", "en"):
        u_ = re.sub(r"-char/(ja|en)/?$", f"-char/{lang}/", url) if "-char/" in url else url
        st, body, final, ctype = http_get_full(u_, accept="text/html")
        v = {"url": u_, "final_url": final, "status": st,
             "fetched_utc": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}
        if st == 200:
            t = body.decode("utf-8", "replace")
            meta = {}
            for m in re.finditer(r"<meta\s+[^>]*>", t, re.I):
                tag = m.group(0)
                nm = re.search(r'name="([^"]+)"', tag)
                ct = re.search(r'content="([^"]*)"', tag)
                if nm and ct and nm.group(1) in JSTAGE_META:
                    meta.setdefault(nm.group(1), []).append(html.unescape(ct.group(1)).strip())
            v["meta"] = meta
            v["sha256"] = hashlib.sha256(body).hexdigest()
        out["views"].append(v)
        if u_ == url and "-char/" not in url:
            break
    path.write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n")
    idx[name] = {"url": url, "status": max((v["status"] or 0) for v in out["views"]),
                 "fetched_utc": out["views"][-1]["fetched_utc"], "stored": str(path.relative_to(ROOT)),
                 "note": "citation_* meta tags of the J-STAGE landing page (ja and en views)"}
    cc.save_index(idx)


def pdf_first_page_text(body):
    """Text of page 1 (pypdf, if importable); the PDF itself is not committed."""
    try:
        import io
        import pypdf  # noqa: F401
        r = pypdf.PdfReader(io.BytesIO(body))
        return ("[page 1 of %d, text extracted with pypdf; PDF metadata CreationDate %s]\n"
                % (len(r.pages), (r.metadata or {}).get("/CreationDate"))) + r.pages[0].extract_text()
    except Exception as exc:  # pragma: no cover
        return f"[text extraction unavailable: {exc!r}]"


# ======================================================================= record readers
def jload(name):
    p = CACHE / name
    return json.loads(p.read_text()) if p.exists() else None


def crossref_msg(name):
    d = jload(name)
    return d["message"] if d else None


def _pick(lst, field, lang="en"):
    lst = lst or []
    for x in lst:
        if x.get("lang") == lang and x.get(field):
            return x[field]
    for x in lst:
        if x.get(field) and not x.get("lang"):
            return x[field]
    return lst[0].get(field) if lst else None


def jalc_msg(key):
    """JaLC record -> a Crossref-shaped message (English values preferred), for crossref_check.compare."""
    d = jload(f"{key}.jalc.json")
    if not d or d.get("status") != "OK":
        return None
    a = d["data"]
    names = []
    for c in sorted(a.get("creator_list") or [], key=lambda c: int(c.get("sequence", 0))):
        ns = c.get("names") or []
        n = next((x for x in ns if x.get("lang") == "en"), ns[0] if ns else {})
        names.append({"family": n.get("last_name", n.get("first_name", "")) if n.get("last_name") else
                      n.get("first_name", ""), "given": n.get("first_name", "") if n.get("last_name") else ""})
    journal = None
    for j in a.get("journal_title_name_list") or []:
        if j.get("type") == "full" and j.get("lang") == "en":
            journal = j["journal_title_name"]
            break
    if journal is None:
        journal = _pick(a.get("journal_title_name_list"), "journal_title_name")
    pd = a.get("publication_date") or {}
    parts = [int(pd[k]) for k in ("publication_year", "publication_month", "publication_day") if pd.get(k)]
    fp, lp = a.get("first_page"), a.get("last_page")
    msg = {"DOI": a["doi"], "type": "jalc:" + a.get("content_type", ""),
           "title": [_pick(a.get("title_list"), "title") or ""],
           "author": [{"family": n["family"], "given": n["given"]} for n in names],
           "container-title": [journal] if journal else [],
           "publisher": _pick(a.get("publisher_list"), "publisher_name") or "",
           "issued": {"date-parts": [parts]} if parts else {}}
    if a.get("volume"):
        msg["volume"] = a["volume"]
    if a.get("issue"):
        msg["issue"] = a["issue"]
    if fp:
        msg["page"] = f"{fp}-{lp}" if lp and lp != fp else fp
    msg["_ja_title"] = _pick(a.get("title_list"), "title", "ja")
    return msg


def _xml_tag(t, tag):
    return [html.unescape(re.sub(r"\s+", " ", x)).strip()
            for x in re.findall(rf"<{tag}(?:\s[^>]*)?>(.*?)</{tag}>", t, re.S)]


def arxiv_msg(key):
    """arXiv OAI-PMH records (arXiv + arXivRaw) -> Crossref-shaped message plus arXiv extras."""
    p, r = CACHE / f"{key}.oai-arxiv.xml", CACHE / f"{key}.oai-arxivraw.xml"
    if not p.exists():
        return None
    t = p.read_text()
    if "<GetRecord>" not in t:
        return None
    t = t[t.index("<metadata>"):]
    authors = []
    for a in re.findall(r"<author>(.*?)</author>", t, re.S):
        authors.append({"family": (_xml_tag(a, "keyname") or [""])[0],
                        "given": (_xml_tag(a, "forenames") or [""])[0]})
    created = _xml_tag(t, "created")[0]
    msg = {"type": "arxiv", "title": [_xml_tag(t, "title")[0]], "author": authors,
           "issued": {"date-parts": [[int(x) for x in created.split("-")]]},
           "_id": _xml_tag(t, "id")[0], "_categories": (_xml_tag(t, "categories") or [""])[0],
           "_doi": (_xml_tag(t, "doi") or [None])[0], "_journal_ref": (_xml_tag(t, "journal-ref") or [None])[0],
           "_versions": []}
    if r.exists():
        rt = r.read_text()
        for v, date in re.findall(r'<version version="(v\d+)">\s*<date>(.*?)</date>', rt, re.S):
            msg["_versions"].append((v, dt.datetime.strptime(date.strip(), "%a, %d %b %Y %H:%M:%S %Z")
                                     .strftime("%Y-%m-%d")))
    return msg


def cinii_msg(key):
    d = jload(f"{key}.cinii.json")
    if not d:
        return None
    title = next((x["@value"] for x in d.get("dc:title", []) if x.get("@language") in (None, "ja", "en")), "")
    authors, kana = [], []
    for c in d.get("creator", []):
        nm = c.get("foaf:name", [])
        plain = next((x["@value"] for x in nm if x.get("@language") != "ja-Kana"), "")
        kana.append(next((x["@value"] for x in nm if x.get("@language") == "ja-Kana"), ""))
        if "," in plain:
            fam, giv = [s.strip() for s in plain.split(",", 1)]
        else:
            toks = plain.split()
            if len(toks) > 1 and toks[0].isupper() and not toks[-1].isupper():
                # B5: CiNii's NII article records write 'FAMILY Given' (e.g. 'SOSIATI Harini')
                fam, giv = toks[0].capitalize(), " ".join(toks[1:])
            else:
                fam, giv = (toks[-1], " ".join(toks[:-1])) if len(toks) > 1 else (plain, "")
        authors.append({"family": fam, "given": giv})
    msg = {"type": "cinii:" + d.get("@type", ""), "title": [title], "author": authors, "_kana": kana,
           "_crid": d["@id"], "_ids": {i["identifier"]["@type"]: i["identifier"]["@value"]
                                       for i in d.get("productIdentifier", [])}}
    pub = d.get("publication") or {}
    if pub:
        msg["container-title"] = [x["@value"] for x in pub.get("prism:publicationName", [])]
        for a, b in (("prism:volume", "volume"), ("prism:number", "issue")):
            if pub.get(a):
                msg[b] = pub[a]
        sp = (pub.get("prism:startingPage") or "").lstrip("p")
        ep = pub.get("prism:endingPage") or ""
        if sp:
            msg["page"] = f"{sp}-{ep}" if ep else sp
        if pub.get("prism:publicationDate"):
            msg["issued"] = {"date-parts": [[int(x) for x in pub["prism:publicationDate"].split("-")]]}
    if d.get("ndl:dateGranted"):
        msg["issued"] = {"date-parts": [[int(x) for x in d["ndl:dateGranted"].split("-")]]}
        msg["_degree"] = (d.get("ndl:degreeName"), d.get("ndl:dissertationNumber"),
                          [x["@value"] for x in (d.get("degreeAwardInstitution") or {}).get("jpcoar:degreeGrantorName", [])])
    return msg


# ======================================================================= katakana reading -> Hepburn
_KANA = dict(zip(
    "ア イ ウ エ オ カ キ ク ケ コ サ シ ス セ ソ タ チ ツ テ ト ナ ニ ヌ ネ ノ ハ ヒ フ ヘ ホ マ ミ ム メ モ ヤ ユ ヨ "
    "ラ リ ル レ ロ ワ ヲ ン ガ ギ グ ゲ ゴ ザ ジ ズ ゼ ゾ ダ ヂ ヅ デ ド バ ビ ブ ベ ボ パ ピ プ ペ ポ".split(),
    "a i u e o ka ki ku ke ko sa shi su se so ta chi tsu te to na ni nu ne no ha hi fu he ho ma mi mu me mo "
    "ya yu yo ra ri ru re ro wa o n ga gi gu ge go za ji zu ze zo da ji zu de do ba bi bu be bo pa pi pu pe po"
    .split()))
_YOON = {"ャ": "a", "ュ": "u", "ョ": "o"}


def kana_to_hepburn(s):
    """Plain Hepburn transcription of a katakana reading (no macrons), e.g. タケグチ -> Takeguchi."""
    out, i = [], 0
    while i < len(s):
        c = s[i]
        if c in _KANA:
            syl = _KANA[c]
            if i + 1 < len(s) and s[i + 1] in _YOON:
                syl = syl[:-1] + ("" if syl in ("shi", "chi", "ji") else "y") + _YOON[s[i + 1]]
                i += 1
            out.append(syl)
        elif c == "ッ" and i + 1 < len(s) and s[i + 1] in _KANA:
            out.append(_KANA[s[i + 1]][0])
        elif c == "ー":
            pass
        else:
            out.append(c)
        i += 1
    return "".join(out)


def kana_name(k):
    fam, _, giv = k.partition(",")
    return kana_to_hepburn(fam.strip()).capitalize(), kana_to_hepburn(giv.strip()).capitalize()


# ======================================================================= comparison
def subentry(e, keep, rename=None):
    """Copy of an Entry holding only the named fields (for scoped comparisons).  B5: the title's inline
    math is reduced to plain text (plain_math) so that SiO$_2$ compares equal to the record's SiO2."""
    rename = rename or {}
    val = lambda f: plain_math(f.value) if f.name == "title" else f.value
    body = ",\n".join(f"  {rename.get(f.name, f.name)} = {{{val(f)}}}" for f in e.fields
                      if f.name in keep)
    txt = f"@{e.etype}{{{e.key},\n{body}\n}}\n" if body else f"@{e.etype}{{{e.key},\n}}\n"
    return bt.parse(txt)[0]


def mathml_to_markup(s):
    """Crossref MathML -> the <sub>/<sup> markup that tex() transcribes (B5): msub/msup of two mi/mn
    leaves, mspace -> space, a space before inline math that follows a letter; other MathML tags dropped."""
    if "mml:" not in (s or ""):
        return s
    leaf = r"\s*(?:<mml:mrow>)?\s*<mml:m[ino][^>]*>([^<]*)</mml:m[ino]>\s*(?:</mml:mrow>)?\s*"
    s = re.sub(r"<mml:msub>" + leaf + leaf + r"</mml:msub>", r"\1<sub>\2</sub>", s)
    s = re.sub(r"<mml:msup>" + leaf + leaf + r"</mml:msup>", r"\1<sup>\2</sup>", s)
    s = re.sub(r"<mml:mspace[^>]*/>", " ", s)
    s = re.sub(r"(?<=[A-Za-z])<mml:math", " <mml:math", s)
    return re.sub(r"</?mml:[^>]*>", "", s)


def norm_record_title(title, key=None, routes=None, log=None):
    """Declared record-title normalisations (B5), each logged in `log`."""
    t0 = title or ""
    t = t0
    if "&amp;" in t:
        t = html.unescape(t)
        log is not None and log.append("the record title is doubly HTML-escaped ('&amp;lt;'); unescaped twice")
    if "mml:" in t:
        t = mathml_to_markup(t)
        log is not None and log.append("the record title's MathML transcribed (subscripts, spaces)")
    if re.search(r"&lt;/?(SUB|SUP|I|B)&gt;", t, re.I):
        t = html.unescape(t)
        log is not None and log.append("the record title's escaped markup (&lt;SUB&gt;) transcribed")
    x = ((routes or {}).get("extra") or {}).get(key) or {}
    pre = x.get("title_prefix")
    if pre:
        if not t.startswith(pre):
            raise SystemExit(f"{key}: declared title_prefix not found in the record title")
        t = t[len(pre):].strip()
        log is not None and log.append(f"the record title carries the issue's feature title '{pre.strip()}' "
                                       "before the article title; that prefix is removed (declared in "
                                       "tools/bib/b5\\_routes.yaml)")
    return t


def clean_msg(msg, key=None, routes=None):
    """Record normalisations applied before comparison and rendering (all logged): J-STAGE deposits issue '0'
    for journals without issues; B5 adds the title normalisations of norm_record_title and, for J-STAGE
    records, drops the closing full stop that J-STAGE deposits after English titles."""
    m = dict(msg)
    m["_norm"] = []
    caps = [a.get("family") for a in m.get("author") or [] if (a.get("family") or "").isupper() and len(a["family"]) > 2]
    if caps:
        m["author"] = [dict(a, family=a["family"].capitalize()) if a.get("family") in caps else a for a in m["author"]]
        m["_norm"].append("family names deposited in capitals (" + ", ".join(caps) + ") read as capitalised")
    if (m.get("container-title") or [""])[0].isupper() and len(m["container-title"][0]) > 3:
        m["_norm"].append(f"container title deposited in capitals ('{m['container-title'][0]}') read as capitalised")
        m["container-title"] = [m["container-title"][0].title()] + list(m["container-title"][1:])
    if str(m.get("issue", "")) == "0":
        m.pop("issue")
        m["_issue0"] = True
    if m.get("title"):
        m["title"] = [norm_record_title(x, key, routes, m["_norm"]) for x in m["title"]]
        x = ((routes or {}).get("extra") or {}).get(key) or {}
        if x.get("title_from_jstage"):
            jm = jstage_msg(key)
            m["title"] = jm["title"]
            m["_norm"].append("the Crossref record's title is empty; the English title of the J-STAGE landing page "
                              f"(citation\\_title, cached as {key}.jstage.json) is used")
        if (m.get("DOI") or "").startswith(JSTAGE_PREFIXES) and m["title"][0].endswith(".") \
                and not m["title"][0].endswith(("al.", "etc.")):
            m["title"] = [m["title"][0][:-1]]
            m["_norm"].append("closing full stop of the J-STAGE record title dropped")
    return m


JSTAGE_PREFIXES = ("10.3131/", "10.1380/", "10.5940/", "10.1541/", "10.2320/", "10.11316/")


def jstage_msg(key):
    """J-STAGE landing-page meta tags -> Crossref-shaped message (Latin-script values only; the English view
    preferred).  Kanji names/titles are kept under _ja for linked-record checks."""
    d = jload(f"{key}.jstage.json")
    if not d:
        return None
    views = [v for v in d["views"] if v.get("status") == 200 and v.get("meta")]
    if not views:
        return None
    meta = views[-1]["meta"]
    latin = lambda s: s and not re.search(r"[\u3000-\u9fff\uff00-\uffef]", s)
    msg = {"DOI": (meta.get("citation_doi") or [""])[0], "type": "jstage-page", "title": [], "author": [],
           "_ja": {"title": [x for x in meta.get("citation_title", []) if not latin(x)],
                   "author": [x for x in meta.get("citation_author", []) if not latin(x)]}}
    tt = [x for x in meta.get("citation_title", []) if latin(x)]
    if tt:
        msg["title"] = [tt[0]]
    for a in meta.get("citation_author", []):
        if latin(a):
            toks = a.split()
            msg["author"].append({"family": toks[-1].capitalize() if toks[-1].isupper() else toks[-1],
                                  "given": " ".join(toks[:-1])})
    jt = [x for x in meta.get("citation_journal_title", []) if latin(x)]
    if jt:
        msg["container-title"] = jt
    for a, b in (("citation_volume", "volume"), ("citation_issue", "issue")):
        if meta.get(a):
            msg[b] = meta[a][0]
    if meta.get("citation_firstpage"):
        fp, lp = meta["citation_firstpage"][0], (meta.get("citation_lastpage") or [""])[0]
        msg["page"] = f"{fp}-{lp}" if lp and lp != fp else fp
    dd = (meta.get("citation_publication_date") or meta.get("citation_date") or [""])[0]
    if dd:
        msg["issued"] = {"date-parts": [[int(z) for z in re.split(r"[/-]", dd) if z]]}
    if not msg["author"]:
        msg.pop("author")
    return msg


def datacite_msg(key):
    """DataCite record -> Crossref-shaped message."""
    d = jload(f"{key}.datacite.json")
    if not d:
        return None
    a = d["data"]["attributes"]
    return {"DOI": a["doi"], "type": "datacite:" + ((a.get("types") or {}).get("resourceTypeGeneral") or ""),
            "title": [(a.get("titles") or [{}])[0].get("title", "")],
            "author": [{"family": c.get("familyName") or c.get("name", ""), "given": c.get("givenName", "")}
                       for c in a.get("creators") or []],
            "container-title": [a.get("publisher") or ""], "publisher": a.get("publisher") or "",
            "issued": {"date-parts": [[int(a["publicationYear"])]]} if a.get("publicationYear") else {},
            "_dates": a.get("dates"), "_rtg": (a.get("types") or {}).get("resourceTypeGeneral")}


_MATH = [(r"$\mu$", "\u03bc"), (r"$<$", "<"), (r"$>$", ">"), (r"$\times$", "\u00d7")]


def plain_math(s):
    """Proposal title -> plain text for comparison: $\\mu$ -> mu sign, $<$ -> <, SiO$_2$ / SiO$_{2}$ -> SiO2."""
    s = s or ""
    for a, b in _MATH:
        s = s.replace(a, b)
    s = re.sub(r"\$_\{?(\w+)\}?\$", r"\1", s)
    s = re.sub(r"\$\^\{?(\w+)\}?\$", r"\1", s)
    return s


def idx_status(idx, name):
    r = idx.get(name) or {}
    return r.get("status"), r.get("url")


def compare_scoped(key, e, msg, scope):
    rename = {"howpublished": "journal"} if "howpublished" in scope else {}
    if e.get("eid") and not e.get("pages") and "pages" in scope:
        rename["eid"] = "pages"             # B5: L9 writes article numbers as eid
        scope = set(scope) | {"eid"}
    sub = subentry(e, scope, rename=rename or None)
    checked, disc, info = cc.compare(key, sub, msg, placeholder=False if sub.get("title") else True)
    out = []
    for f, b, r, kind in disc:
        if f == "title" and b == "(placeholder)":
            continue
        if f.split("[")[0].split("-")[0] not in {"author", "editor", "title", "container", "volume", "issue",
                                                  "pages", "year", "publisher"} or \
                (f == "year" and "year" not in scope) or (f == "container-title" and not scope & {"journal", "booktitle", "howpublished"}):
            continue
        if r in ("(none)", "", None) or (isinstance(r, str) and r.startswith("(none)")):
            kind = "record-silent"          # the record does not carry this field: nothing to compare
        elif kind.startswith("ratio=") and bt.fold(b).replace(" ", "") == bt.fold(r).replace(" ", ""):
            kind = "spacing"                # differs only in white space (e.g. CiNii '(110)Surface')
        elif kind == "given" and bt.initials(b) == bt.initials(r):
            kind = "given-form"             # B5: 'David R. G.' vs 'D.R.G.' (same initials; comparator folds 'D.R.G.' to one token)
        elif f == "volume" and str(b).replace("\u2013", "-") == str(r):
            kind = "dash-form"              # B5: '100--101' (en dash) vs record '100-101'
        out.append({"field": f, "proposal": b, "record": r, "kind": kind})
    return checked, out, info


NONCOUNT = {"record-silent", "spacing", "given-form", "dash-form"}     # logged, not counted as mismatches


def date_claims(text):
    months = "January February March April May June July August September October November December".split()
    out = []
    for d, mo, y in re.findall(r"(\d{1,2}) (" + "|".join(months) + r") (\d{4})", text or ""):
        out.append(f"{y}-{months.index(mo) + 1:02d}-{int(d):02d}")
    return out


def check_entry(src, e, routes, idx):
    """Return the per-entry result dict (no side effects)."""
    k = e.key
    x = (routes.get("extra") or {}).get(k) or {}
    res = {"src": src, "key": k, "etype": e.etype, "doi": e.get("doi") or "", "eprint": arxiv_id(e) or "",
           "routes": [], "checked": [], "mism": [], "format": [], "info": [], "records": {}}

    def route(label, name):
        st, url = idx_status(idx, name)
        res["routes"].append(f"{label} {url} -> HTTP {st}")
        return st

    # ---------------- formatting of the proposal itself (fixed by rendering from the record)
    t = e.get("title") or ""
    if t.startswith("{") and t.endswith("}") and bt._match_brace(t, 0) == len(t):
        res["format"].append("title wrapped in a second brace pair (suppresses all case handling)")
    for f in e.fields:
        if f.name != "note" and any(ord(c) > 127 for c in f.value) and not (
                e.etype == "phdthesis" and f.name in ("title", "school", "type")):   # Japanese kept (UTF-8)
            res["format"].append(f"{f.name}: raw non-ASCII characters (references.bib is LaTeX-encoded)")
        if "\\\\&" in f.value:
            res["format"].append(f"{f.name}: doubled backslash before the ampersand (a LaTeX line break), "
                                 "not an escaped ampersand")
    for n in bt.split_names(e.get("author") or ""):
        pn = bt.parse_name(n)
        if pn.get("family") and pn["family"].isupper() and len(pn["family"]) > 2:
            res["format"].append(f"author family name in capitals as deposited: {pn['family']}")
        if n.count(",") > 1 or "(" in n:
            res["format"].append(f"author '{n}' is not a parseable BibTeX name")
    if (e.get("number") or "") == "0":
        res["format"].append("number = {0}: J-STAGE's placeholder issue for journals without issues")
    if e.get("author") is not None and not (e.get("author") or "").strip():
        res["format"].append("empty author field")
    for f in e.fields:
        if f.name not in ("url", "doi", "eprint", "note", "urldate") and re.search(r"(?<!\\)_", re.sub(r"\$[^$]*\$", "", f.value)):
            res["format"].append(f"{f.name}: unescaped underscore")
    if e.get("eid"):
        res["format"].append("article number in an eid field (references.bib writes article numbers as pages)")

    doi = e.get("doi")
    main = None
    if doi:
        st = route("Crossref", f"{k}.json")
        if st == 200:
            main = ("Crossref", f"{k}.json", clean_msg(crossref_msg(f"{k}.json"), k, routes))
        else:
            route("doi.org/ra", f"{k}.ra.json")
            if (CACHE / f"{k}.jalc.json").exists():
                route("JaLC", f"{k}.jalc.json")
                main = ("JaLC", f"{k}.jalc.json", clean_msg(jalc_msg(k), k, routes))
            elif (CACHE / f"{k}.datacite.json").exists():
                route("DataCite", f"{k}.datacite.json")
                main = ("DataCite", f"{k}.datacite.json", clean_msg(datacite_msg(k), k, routes))
        if main:
            res["norm"] = list(main[2].get("_norm") or [])
    am = None
    if arxiv_id(e):
        route("arXiv query API", f"{k}.arxiv.xml")
        route("arXiv OAI-PMH (arXiv)", f"{k}.oai-arxiv.xml")
        route("arXiv OAI-PMH (arXivRaw)", f"{k}.oai-arxivraw.xml")
        am = arxiv_msg(k)
    cm = None
    if x.get("cinii"):
        route("CiNii Research", f"{k}.cinii.json")
        cm = cinii_msg(k)
    if (CACHE / f"{k}.arxivdoi.json").exists():
        route("Crossref (DOI named in the arXiv record)", f"{k}.arxivdoi.json")
    if x.get("claim_doi"):
        route("Crossref (DOI claimed in the report)", f"{k}.claim.json")
    if x.get("pdf"):
        route("publisher file (PDF, title page)", f"{k}.titlepage.txt")

    def add(label, checked, mism):
        res["checked"] += [f"{c}({label})" for c in checked]
        for m in mism:
            m["source"] = label
            res["mism"].append(m)

    thesis = e.etype == "phdthesis"
    if main and not thesis:
        label, name, msg = main
        res["records"]["main"] = (label, name)
        scope = {"author", "title", "journal", "booktitle", "volume", "number", "pages", "year", "publisher",
                 "howpublished"}
        if label in ("JaLC", "DataCite"):
            scope.discard("publisher")
        ch, mm, info = compare_scoped(k, e, msg, scope)
        if msg.get("_issue0"):
            res["info"].append(f"{label} record deposits issue '0' (read as: no issue)")
        if doi.lower() != (msg.get("DOI") or "").lower():
            mm.append({"field": "doi", "proposal": doi, "record": msg.get("DOI"), "kind": "doi"})
        rtype = msg.get("type")
        want = {"journal-article": "article", "book-chapter": "incollection", "jalc:JA": ("article", "misc")}
        if rtype in want and e.etype not in (want[rtype] if isinstance(want[rtype], tuple) else (want[rtype],)):
            mm.append({"field": "@type", "proposal": e.etype, "record": rtype, "kind": "type"})
        res["info"].append(f"{label} dates: {cc.cr_years(msg)}; year matches {info.get('year_matches')}")
        add(label, ch, mm)
    if am:
        res["records"]["arxiv"] = f"{k}.oai-arxiv.xml"
        scope = {"author", "title"} if e.get("journal") else {"author", "title", "year"}
        v1 = am["_versions"][0][1] if am["_versions"] else None
        amsg = dict(am)
        if v1:
            amsg["issued"] = {"date-parts": [[int(z) for z in v1.split("-")]]}
        ch, mm, info = compare_scoped(k, e, amsg, scope)
        if am["_id"] != arxiv_id(e):
            mm.append({"field": "eprint", "proposal": arxiv_id(e), "record": am["_id"], "kind": "eprint"})
        blob = " ".join(e.get(f) or "" for f in ("howpublished", "note"))
        vers = dict(am["_versions"])
        for v in set(re.findall(re.escape(arxiv_id(e)) + r"(v\d+)", blob)):
            ch.append(f"version {v}")
            if v not in vers:
                mm.append({"field": "version", "proposal": v, "record": ", ".join(vers), "kind": "version"})
        for d in date_claims(e.get("howpublished") or "") + (date_claims(e.get("note") or "")[:1] if arxiv_id(e) else []):
            ch.append(f"date {d}")
            if d not in vers.values():
                mm.append({"field": "date", "proposal": d, "record": "; ".join(f"{a} {b}" for a, b in vers.items()),
                           "kind": "date"})
        m = re.search(r"\[([\w.\-]+)\]", e.get("howpublished") or "")
        if m:
            ch.append("primary category")
            if m.group(1) != am["_categories"].split()[0]:
                mm.append({"field": "category", "proposal": m.group(1), "record": am["_categories"], "kind": "category"})
        res["info"].append(f"arXiv versions {am['_versions']}; categories '{am['_categories']}'; "
                           f"journal-ref {am['_journal_ref']!r}; doi {am['_doi']!r}")
        add("arXiv", ch, mm)
    if cm and not thesis:
        res["records"]["cinii"] = f"{k}.cinii.json"
        ch, mm, info = compare_scoped(k, e, cm, {"author", "title", "journal", "volume", "number", "pages", "year"})
        add("CiNii", ch, mm)
        res["info"].append("CiNii record " + cm["_crid"].replace(".json", "") + ": authors "
                           + "; ".join(f"{a['family']}, {a['given']}" for a in cm["author"]))
    # ---------------- B5 routes
    if x.get("jstage"):
        route("J-STAGE landing page (citation meta tags)", f"{k}.jstage.json")
        jm = jstage_msg(k)
        if jm:
            res["records"]["jstage"] = f"{k}.jstage.json"
            ch, mm, info = compare_scoped(k, e, jm, {"author", "title", "journal", "volume", "number", "pages",
                                                     "year"})
            if jm.get("DOI", "").lower() != (doi or "").lower():
                mm.append({"field": "doi", "proposal": doi, "record": jm.get("DOI"), "kind": "doi"})
            add("J-STAGE", ch, mm)
            res["info"].append("J-STAGE page: title " + json.dumps(jm.get("title") + jm["_ja"]["title"], ensure_ascii=False)
                               + "; authors " + json.dumps([f"{a['family']}, {a['given']}" for a in jm.get("author", [])]
                                                           + jm["_ja"]["author"], ensure_ascii=False))
    if x.get("linked_name"):
        ln = x["linked_name"]
        jm = jstage_msg(k)
        other = jload(f"{ln['jalc_key']}.jalc.json")["data"]
        cr = next(c for c in other["creator_list"] if int(c["sequence"]) == int(ln["seq"]))
        ja = next(n for n in cr["names"] if n.get("lang") == "ja")
        en = next(n for n in cr["names"] if n.get("lang") == "en")
        kanji = jm["_ja"]["author"][0] if jm and jm["_ja"]["author"] else ""
        same = kanji.replace(" ", "").replace("\u3000", "") == ja["last_name"] + ja["first_name"]
        prop = bt.parse_name(bt.split_names(e.get("author") or "")[0])
        res["checked"].append("author(linked records)")
        res["linked"] = {"kanji": kanji, "other_key": ln["jalc_key"], "other_ja": ja["last_name"] + " " + ja["first_name"],
                         "other_en": f"{en['last_name']}, {en['first_name']}", "same_kanji": same,
                         "given_equal": bt.fold(en["first_name"]) == bt.fold(prop["given"]),
                         "family_equal": bt.fold(en["last_name"]) == bt.fold(prop["family"])}
        if not same or not res["linked"]["given_equal"]:
            res["mism"].append({"field": "author(linked records)", "proposal": e.get("author"),
                                "record": json.dumps(res["linked"], ensure_ascii=False), "kind": "family",
                                "source": "linked records"})
    if x.get("alt_doi"):
        route("Crossref (second DOI named in the note)", f"{k}.altdoi.json")
        alt = crossref_msg(f"{k}.altdoi.json")
        if alt:
            ch, mm, info = compare_scoped(k, e, clean_msg(alt, k, routes), {"author", "title", "journal", "volume",
                                                                           "number", "pages", "year"})
            bad = [m for m in mm if m["kind"] not in NONCOUNT]
            res["info"].append(f"second Crossref record {alt.get('DOI')}: "
                               + ("every compared field agrees with the proposal" if not bad else json.dumps(bad)))
            res["alt"] = {"doi": alt.get("DOI"), "agree": not bad}
    if x.get("crossref_query"):
        route("Crossref bibliographic query", f"{k}.crquery.json")
        q = jload(f"{k}.crquery.json")
        items = (q or {}).get("message", {}).get("items", [])
        hit = [it["DOI"] for it in items if bt.fold(" ".join(it.get("title") or [])) == bt.fold(plain_math(e.get("title") or ""))]
        res["crquery"] = {"query": x["crossref_query"], "n": len(items), "title_match": hit,
                          "top": [f"{it['DOI']} '{' '.join(it.get('title') or [])[:60]}'" for it in items[:3]]}
        res["info"].append(f"Crossref query.bibliographic '{x['crossref_query']}': {len(items)} results, "
                           + (f"TITLE MATCH {hit}" if hit else "none with the entry's title"))
    pages = x.get("page") or []
    if pages:
        names = []
        for i, pg in enumerate(pages, 1):
            nm = f"{k}.page{i}.json"
            st = route(f"page {i}", nm)
            names.append(nm)
            d = jload(nm) or {}
            if d.get("status") != 200:
                res["mism"].append({"field": f"page {i}", "proposal": pg["url"], "record": f"HTTP {d.get('status')}",
                                    "kind": "page", "source": "page"})
                continue
            for c in d.get("checks", []):
                res["checked"].append(f"{c['what']}(page {i})")
                if not c["found"]:
                    res["mism"].append({"field": c["what"], "proposal": c["string"], "record": "not found on the page",
                                        "kind": "page", "source": f"page {i}"})
        if not main:
            res["records"]["main"] = ("page", names)
    for a in x.get("aux") or []:
        st = route(a.get("label", a["name"]), f"{k}.{a['name']}.json")
        d = jload(f"{k}.{a['name']}.json") if st == 200 else None
        summ = ""
        if d and a["name"] == "openalex":
            summ = "authorships: " + "; ".join(f"{z['author']['display_name']} (raw name '{z.get('raw_author_name')}', "
                                               f"is_corresponding {z.get('is_corresponding')})" for z in d.get("authorships", []))
        elif d and a["name"] == "s2":
            summ = "authors: " + "; ".join(z["name"] for z in d.get("authors", []))
        res.setdefault("aux", {})[a["name"]] = {"status": st, "summary": summ}
        res["info"].append(f"{a.get('label', a['name'])}: HTTP {st}" + (f" -- {summ}" if summ else ""))
    if x.get("wp_rest"):
        route("WordPress REST record of the page", f"{k}.wprest.json")
        w = jload(f"{k}.wprest.json")
        if w:
            res["wp"] = {"created": w[0].get("date"), "modified": w[0].get("modified")}
            res["info"].append(f"site REST record: page created {w[0].get('date')}, modified {w[0].get('modified')}")
    if thesis:
        jm = jalc_msg(k) if (CACHE / f"{k}.jalc.json").exists() else None
        res["records"]["main"] = ("JaLC", f"{k}.jalc.json")
        res["records"]["cinii"] = f"{k}.cinii.json"
        ch, mm = [], []
        bt_title = unicodedata_nfkc(bt.latex_to_unicode(e.get("title") or ""))
        ch.append("title")
        if jm and bt_title != unicodedata_nfkc(jm["title"][0]):
            mm.append({"field": "title", "proposal": bt_title, "record": jm["title"][0], "kind": "title"})
        a = e.get("author") or ""
        jname = (jm["author"][0]["family"] if jm and jm["author"] else "")
        ch.append("author")
        kanji = a.split("(")[0].strip()
        if unicodedata_nfkc(kanji).replace(" ", "") != unicodedata_nfkc(jname).replace(" ", ""):
            mm.append({"field": "author(kanji)", "proposal": kanji, "record": jname, "kind": "family"})
        if cm and cm.get("_kana"):
            fam, giv = kana_name(cm["_kana"][0])
            rom = re.search(r"\(([^)]*)\)", a)
            rom = rom.group(1) if rom else ""
            if rom and bt.fold(rom) != bt.fold(f"{fam}, {giv}"):
                mm.append({"field": "author(romanised)", "proposal": rom,
                           "record": f"{cm['_kana'][0]} = {fam}, {giv}", "kind": "family"})
            res["info"].append(f"CiNii reading {cm['_kana'][0]} -> Hepburn '{fam}, {giv}'")
        ch.append("year")
        yj = str((jm or {}).get("issued", {}).get("date-parts", [[None]])[0][0])
        yc = str((cm or {}).get("issued", {}).get("date-parts", [[None]])[0][0])
        if e.get("year") not in (yj, yc):
            mm.append({"field": "year", "proposal": e.get("year"), "record": f"JaLC {yj}; CiNii {yc}", "kind": "year"})
        if cm and cm.get("_degree"):
            deg, num, grantor = cm["_degree"]
            ch += ["school", "type"]
            if not any(g in (e.get("school") or "") for g in grantor):
                mm.append({"field": "school", "proposal": e.get("school"), "record": "; ".join(grantor), "kind": "school"})
            ty = unicodedata_nfkc(e.get("type") or "").replace(" ", "")
            for part in (deg, num):
                if part and unicodedata_nfkc(part).replace(" ", "") not in ty:
                    mm.append({"field": "type", "proposal": e.get("type"), "record": part, "kind": "type"})
            res["info"].append(f"CiNii degree {deg}, {num}, grantor {grantor}, date granted {cm['issued']}")
            doi_ok = (cm.get("_ids") or {}).get("DOI", "").lower() == (doi or "").lower()
            ch.append("doi(CiNii)")
            if not doi_ok:
                mm.append({"field": "doi", "proposal": doi, "record": (cm.get("_ids") or {}).get("DOI"), "kind": "doi"})
        add("JaLC+CiNii", ch, mm)
    if x.get("claim_doi"):
        crm = crossref_msg(f"{k}.claim.json")
        if crm and not x.get("claim_only_report"):
            # the report names a different DOI for this work: test the report's claim on the five-field
            # rule, then compare every proposal field with that record as well
            claimed = cc.claimed_entry(k, {"type": "article", "claimed": x["claimed"], "source": src})
            ev = cc.evaluate_candidate(k, claimed, crm)
            res["claim"] = {"doi": crm.get("DOI"), "verdict": ev["verdict"],
                            "tests": {a: b for a, b in ev.items() if a != "verdict"}}
            ch, mm, info = compare_scoped(k, e, clean_msg(crm), {"author", "title", "journal", "volume", "number",
                                                                  "pages", "year"})
            if doi and doi.lower() != crm["DOI"].lower():
                mm.append({"field": "doi", "proposal": doi, "record": crm["DOI"], "kind": "doi"})
            add("Crossref(claimed DOI)", ch, mm)
            res["records"]["claim"] = f"{k}.claim.json"
        elif crm:
            res["info"].append(f"Crossref record of the DOI named by the report/preprint {crm.get('DOI')}: title "
                               f"'{cc.cr_title(crm)}', container {crm.get('container-title')}, volume {crm.get('volume')}, "
                               f"issue {crm.get('issue')}, article {crm.get('article-number') or crm.get('page')}, "
                               f"authors {len(crm.get('author') or [])}")
    if (CACHE / f"{k}.arxivdoi.json").exists():
        crm = crossref_msg(f"{k}.arxivdoi.json")
        ch, mm, info = compare_scoped(k, e, crm, {"author", "title"})
        res["info"].append(f"journal version named in the arXiv record: {crm.get('DOI')}, "
                           f"{crm.get('container-title')} {crm.get('volume')}, {crm.get('article-number') or crm.get('page')}, "
                           f"title '{cc.cr_title(crm)}'; authors/title vs proposal: "
                           + ("agree" if not [m for m in mm if m['kind'] not in NONCOUNT] else json.dumps(mm)))
    if x.get("pdf"):
        p = CACHE / f"{k}.titlepage.txt"
        txt = p.read_text() if p.exists() else ""
        res["records"]["main"] = ("publisher file", f"{k}.titlepage.txt")
        ch, mm = ["title", "author"], []
        flat = re.sub(r"\s+", " ", txt.replace("µ", "u").replace("μ", "u"))
        tt = bt.latex_to_unicode(e.get("title") or "").replace("$\\mu$", "u").replace("$", "").replace("\\mu", "u")
        main_t = re.sub(r"\s*\(manual\)$", "", tt)
        for part in re.split(r":\s*", main_t):
            if bt.fold(part) not in bt.fold(flat):
                mm.append({"field": "title", "proposal": part, "record": flat[:160], "kind": "title"})
        auth_line = next((ln for ln in txt.splitlines() if "Allen" in ln and "," in ln), "")
        for i, n in enumerate(bt.split_names(e.get("author") or "")):
            fam = bt.parse_name(n)["family"]
            if bt.fold(fam) not in bt.fold(auth_line):
                mm.append({"field": f"author[{i+1}]", "proposal": fam, "record": auth_line, "kind": "family"})
        if "(manual)" in tt:
            mm.append({"field": "title", "proposal": tt, "record": "title page prints no '(manual)'",
                       "kind": "title-extra"})
        res["info"].append("title page: " + flat[:200])
        add("PDF title page", ch, mm)
    return res


def unicodedata_nfkc(s):
    import unicodedata
    return unicodedata.normalize("NFKC", s or "").strip()


def oup_locator(msg):
    """(volume, issue, first page) encoded in an academic.oup.com resource/link URL of a Crossref record."""
    urls = [((msg.get("resource") or {}).get("primary") or {}).get("URL", "")]
    urls += [l.get("URL", "") for l in msg.get("link") or []]
    for u_ in urls:
        m = re.search(r"academic\.oup\.com/\w+/article(?:-pdf)?/(\d+)/(\d+)/(\d+)/", u_ or "")
        if m:
            return m.groups(), u_
    return None, None


# ======================================================================= duplicates
def first_family(e):
    names = bt.split_names(e.get("author") or "")
    if not names:
        return ""
    fam = bt.parse_name(names[0]).get("family", "")
    if "(" in names[0]:                                  # 'kanji, kanji (Roman, Name)'
        m = re.search(r"\(([^,()]+),", names[0])
        fam = m.group(1) if m else fam
    return bt.fold(fam)


def same_work(a, b):
    """Title similarity if a and b could be one work (same first-author family name); 0 otherwise."""
    ta, tb = bt.fold(a.get("title") or ""), bt.fold(b.get("title") or "")
    if not ta or not tb:
        return 0.0
    r = difflib.SequenceMatcher(None, ta, tb).ratio()
    return r if first_family(a) and first_family(a) == first_family(b) else 0.0


def distinct_items(a, b):
    """Two differently registered DOIs, or different years: separate items even if the titles agree
    (e.g. a meeting abstract and the later paper of the same title)."""
    da, db = (a.get("doi") or "").lower(), (b.get("doi") or "").lower()
    return bool(da and db and da != db) or (a.get("year") and b.get("year") and a.get("year") != b.get("year"))


def find_duplicates(props, base):
    """{key: (kind, other_key, detail)} against the baseline bib and between the proposals."""
    out, near = {}, []
    bdoi = {(e.get("doi") or "").lower(): e.key for e in base if e.get("doi")}
    barx = {arxiv_id(e): e.key for e in base if arxiv_id(e)}
    bkey = {e.key.lower(): e for e in base}
    for src, e in props:
        d = (e.get("doi") or "").lower()
        if e.key.lower() in bkey and not (d and d == (bkey[e.key.lower()].get("doi") or "").lower()):
            out[e.key] = ("references.bib", bkey[e.key.lower()].key, "same key, different item (key collision)")
        elif d and d in bdoi:
            out[e.key] = ("references.bib", bdoi[d], "same DOI")
        elif arxiv_id(e) and arxiv_id(e) in barx:
            out[e.key] = ("references.bib", barx[arxiv_id(e)], "same arXiv id")
        else:
            for b in base:
                r = same_work(e, b)
                if r >= 0.90 and distinct_items(e, b):
                    near.append((e.key, b.key, round(r, 2), "same first author and title but "
                                 + ("different DOI" if e.get("doi") and b.get("doi") else "different year")
                                 + f" ({e.get('year')} vs {b.get('year')}): separate item, not a duplicate"))
                elif r >= 0.90:
                    out[e.key] = ("references.bib", b.key, f"same first author, title similarity {r:.2f}")
                    break
                elif r >= 0.60:
                    near.append((e.key, b.key, round(r, 2), "related title, same first author"))
    for i, (sa, a) in enumerate(props):
        for sb, b in props[i + 1:]:
            if sa == sb:
                continue
            da, db = (a.get("doi") or "").lower(), (b.get("doi") or "").lower()
            why = "same DOI" if da and da == db else (
                "same arXiv id" if arxiv_id(a) and arxiv_id(a) == arxiv_id(b) else None)
            r = same_work(a, b)
            if not why and distinct_items(a, b):
                r = min(r, 0.89)
            if why or r >= 0.90:
                why = why or f"same first author, title similarity {r:.2f}"
                out.setdefault(b.key, (sa, a.key, why))
                out.setdefault(a.key, (sb, b.key, why))
            elif r >= 0.60:
                near.append((a.key, b.key, round(r, 2), "related title, same first author (L8 vs L9)"))
    return out, near


def baseline_text(routes):
    return subprocess.run(["git", "-C", str(ROOT), "show", f"{routes['baseline_rev']}:docs/references.bib"],
                          check=True, capture_output=True, text=True).stdout


# ======================================================================= evaluate everything
def evaluate():
    routes = load_routes()
    idx = cc.load_index()
    props = proposals()
    base_text = baseline_text(routes)
    base = bt.parse(base_text)
    dups, near = find_duplicates(props, base)
    keep = routes.get("keep_on_duplicate") or {}
    results = []
    for src, e in props:
        r = check_entry(src, e, routes, idx)
        counted = [m for m in r["mism"] if m["kind"] not in NONCOUNT]
        resid = (routes.get("accepted_residual") or {}).get(e.key, "")
        for m in counted:
            m["resolution"] = ("proposal kept (record artefact; tools/bib/b5_routes.yaml accepted_residual)"
                               if resid and any(s.startswith(m["field"] + ":") for s in
                                                (resid if isinstance(resid, list) else [resid]))
                               else "corrected to the record value")
        r["counted"] = counted
        d = dups.get(e.key)
        r["dup"] = d
        # ---- verdict
        if e.key == "TAKEGUCHI1990":
            r.update(verdict_takeguchi(r, e, base))
        elif e.key in (routes.get("not_merged") or {}):
            r["verdict"], r["action"] = "NOT-MERGED", "not merged: " + routes["not_merged"][e.key]
        elif d and "key collision" in d[2]:
            r["verdict"], r["action"] = "NOT-MERGED", f"not merged (key collision with references.bib [{d[1]}])"
        elif d and d[0] == "references.bib":
            r["verdict"], r["action"] = "DUPLICATE", f"not merged (duplicate of references.bib [{d[1]}], {d[2]})"
        elif d and keep.get(e.key) == d[1]:
            r["verdict"], r["action"] = "DUPLICATE", f"not merged (duplicate of {d[0]} [{d[1]}], {d[2]}; notes combined)"
        elif not r["records"]:
            r["verdict"], r["action"] = "NOT-MERGED", "not merged (no registry record and no page route)"
        elif r["records"].get("main", ("",))[0] == "page":
            if counted:
                r["verdict"], r["action"] = "NOT-MERGED", "not merged (page check failed)"
            else:
                r["verdict"], r["action"] = "PAGE-CHECKED", "merged; proposal fields as checked on the page"
        elif r.get("claim") and not r["claim"]["verdict"].startswith("ACCEPT"):
            r["verdict"], r["action"] = "NOT-MERGED", "not merged (claimed DOI not accepted)"
        elif [m for m in counted if m["resolution"].startswith("corrected")]:
            r["verdict"], r["action"] = "VERIFIED-CORRECTED", "merged; fields from the record"
        else:
            r["verdict"], r["action"] = "VERIFIED", "merged; fields from the record"
        results.append(r)
    return routes, props, base_text, results, near


def verdict_takeguchi(r, e, base):
    """Apply the proposed correction only if CiNii/NDL confirms it (task instruction)."""
    old = next(b for b in base if b.key == "TAKEGUCHI1990")
    crm = crossref_msg("TAKEGUCHI1990.json")
    loc, url = oup_locator(crm)
    cin = [m for m in r["mism"] if m["source"] == "CiNii" and m["kind"] not in NONCOUNT]
    cr = [m for m in r["mism"] if m["source"] == "Crossref" and m["kind"] not in NONCOUNT]
    tests = {"CiNii": "confirms author list, title, journal, volume, issue, pages, year" if not cin else json.dumps(cin),
             "Crossref": "title, journal, year agree; record has no authors, volume or pages" if not cr else json.dumps(cr),
             "locator": f"{loc} in {url}"}
    ok = not cin and not cr and loc == (e.get("volume"), e.get("number"), bib_first_page(e))
    r["takeguchi"] = {"old": {f.name: f.value for f in old.fields if f.name != "note"}, "tests": tests, "ok": ok}
    if ok:
        return {"verdict": "CORRECTION-CONFIRMED", "action": "references.bib [TAKEGUCHI1990] corrected and moved "
                                                              "from the UNVERIFIED section"}
    return {"verdict": "CORRECTION-NOT-CONFIRMED", "action": "references.bib [TAKEGUCHI1990] left unchanged"}


def bib_first_page(e):
    return (bt.latex_to_unicode(e.get("pages") or "").replace("–", "-").split("-")[0]).strip()


# ======================================================================= rendering
_PH = {"×": "@@TIMES@@", "√": "@@SQRT@@", "µ": "@@MU@@", "μ": "@@MU@@"}


def tex(s):
    """Record text -> BibTeX value (LaTeX-encoded ASCII; markup transcribed).  B5: markup tags matched
    case-insensitively (J-STAGE deposits <SUB>); a literal < or > is written $<$ / $>$."""
    t = html.unescape(s or "")
    t = re.sub(r"(?i)(?<=[A-Za-z])<i>([A-Za-z])</i>", r" @@I\1@@", t)
    t = re.sub(r"(?i)<i>([A-Za-z])</i>", r"@@I\1@@", t)
    t = re.sub(r"(?i)<sub>(\w+)</sub>", r"@@SUB\1@@", t)
    t = re.sub(r"(?i)<sup>(\w+)</sup>", r"@@SUP\1@@", t)
    t = re.sub(r"(?i)(?<=[.\w])<b>(.*?)</b>", r" \1", t)
    t = re.sub(r"<[^<>]+>", "", t)
    t = t.replace("<", "@@LT@@").replace(">", "@@GT@@")
    t = re.sub(r"\s+", " ", t).strip()
    t = re.sub(r"\s+([:;,])", r"\1", t)             # XML line breaks before punctuation (e.g. NI26)
    for a, b in _PH.items():
        t = t.replace(a, b)
    t, bad = bt.unicode_to_latex(t)
    t = re.sub(r"@@SQRT@@(\d+)", r"$\\sqrt{\1}$", t)
    t = t.replace("@@TIMES@@", "$\\times$").replace("@@MU@@", "$\\mu$")
    t = t.replace("@@LT@@", "$<$").replace("@@GT@@", "$>$")
    t = re.sub(r"@@I(\w)@@", r"$\1$", t)
    t = re.sub(r"@@SUB(\w+)@@", r"$_{\1}$", t)
    t = re.sub(r"@@SUP(\w+)@@", r"$^{\1}$", t)
    return t, bad


def cr_title_raw(msg):
    """Crossref-shaped title with its markup kept (tex() transcribes it)."""
    t = " ".join(msg.get("title") or [])
    sub = " ".join(msg.get("subtitle") or [])
    return t + (": " + sub if sub and bt.fold(sub) not in bt.fold(t) else "")


def names_tex(msg):
    out = []
    for n in cc.names_of(msg, "author"):
        fam = n["family"]
        if fam.isupper() and len(fam) > 2:
            fam = fam.capitalize()                   # J-STAGE deposits some family names in capitals
        out.append({"family": fam, "given": n["given"]})
    return cc.fmt_names(out)


def l_label(note):
    """The evidence label of an L6/L7 note: text after 'evidence:' up to the first ';' or '. ' at
    parenthesis depth 0."""
    t = re.sub(r"^\s*evidence:\s*", "", note or "")
    depth = 0
    for i, c in enumerate(t):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif depth == 0 and (c == ";" or (c == ":" and t[i + 1:i + 2] == " ") or
                             (c == "." and t[i + 1:i + 2] == " " and not t[i + 2:i + 3][:1].isdigit()
                                          and not re.search(r"(?:\b(?:sec|secs|p|pp|Eq|Eqs|Fig|Figs|No|vol|Ref|al|"
                                                            r"cf|Tab|ch)|\b[A-Z])$", t[:i]))):
            return t[:i].strip(), t[i + 1:].strip()
    return t.strip(), ""


SCRATCH_SENT = re.compile(r"\s*Crossref record cached by L6 as scratchpad [^;]*?; fields copied from it\.")


def evidence_prefix(label, src):
    parts = []
    if "SECTION\\_READ" in label:
        parts.append(f"SECTION\\_READ (as labelled by {src}; not re-checked in B4)")
    for a in re.findall(r"\+ABSTRACT\([^)]*\)", label):
        parts.append(f"{a} (as labelled by {src})")
    return parts


def fmt_date(iso):
    y, m, d = iso.split("-")
    months = "January February March April May June July August September October November December".split()
    return f"{int(d)} {months[int(m) - 1]} {y}"


def render(r, e, routes, extra_notes=()):
    """Return (etype, [(field, value)]) for the merged entry, and a list of what was copied/set."""
    k, src = r["key"], r["src"]
    sets = (routes.get("set") or {}).get(k) or {}
    f = {}
    rec_name = None
    etype = e.etype
    if r.get("claim"):
        msg = clean_msg(crossref_msg(f"{k}.claim.json"))
        rec_name = f"{k}.claim.json"
    elif r["records"].get("main") and r["records"]["main"][0] in ("Crossref", "JaLC") and etype != "phdthesis":
        label, rec_name = r["records"]["main"]
        msg = clean_msg(crossref_msg(rec_name) if label == "Crossref" else jalc_msg(k))
    else:
        msg = None
    if msg is not None and etype in ("article", "misc", "incollection") and not arxiv_only(e):
        f["author"] = names_tex(msg)
        f["title"] = tex(cr_title_raw(msg))[0]
        cont = tex((msg.get("container-title") or [""])[0])[0]
        if etype == "incollection":
            f["booktitle"] = cont
            f["publisher"] = tex(msg.get("publisher", ""))[0]
        elif etype == "article":
            f["journal"] = cont
        else:
            f["howpublished"] = cont
        if msg.get("volume"):
            f["volume"] = str(msg["volume"])
        if msg.get("issue"):
            f["number"] = re.sub(r"^(\w+)-(\w+)$", r"\1--\2", str(msg["issue"]))
        a, b = cc.cr_pages(msg)
        if a:
            f["pages"] = f"{a}--{b}" if b and b != a else a
        y = cc.cr_years(msg)
        f["year"] = (y.get("published-print") or y.get("issued")).split("-")[0]
        f["doi"] = msg["DOI"]
        if e.get("eprint"):
            f["eprint"], f["archiveprefix"] = e.get("eprint"), "arXiv"
    elif arxiv_only(e):
        am = arxiv_msg(k)
        f["author"] = cc.fmt_names(am["author"])
        f["title"] = tex(am["title"][0])[0]
        v1 = am["_versions"][0]
        vl = am["_versions"][-1]
        f["year"] = v1[1][:4]
        f["eprint"], f["archiveprefix"] = am["_id"], "arXiv"
        hp = f"arXiv preprint arXiv:{am['_id']}{vl[0]} [{am['_categories'].split()[0]}], v1 submitted {fmt_date(v1[1])}"
        if vl[0] != "v1":
            hp += f", {vl[0]} {fmt_date(vl[1])}"
        f["howpublished"] = hp
    elif etype == "phdthesis":
        jm, cm = jalc_msg(k), cinii_msg(k)
        fam, giv = kana_name(cm["_kana"][0])
        f["author"] = f"{fam}, {giv}"
        f["title"] = jm["title"][0]
        f["school"] = e.get("school")
        f["type"] = e.get("type")
        f["year"] = str(cm["issued"]["date-parts"][0][0])
        f["doi"] = jm["DOI"]
    else:                                   # manual: proposal fields, checked against the title page
        for fld in e.fields:
            if fld.name != "note":
                f[fld.name] = fld.value
        t = f.get("title", "")
        if t.startswith("{") and t.endswith("}"):
            f["title"] = t[1:-1]
    for a, b in sets.items():
        f[a] = str(b)
    return etype, f, rec_name


def arxiv_only(e):
    return bool(arxiv_id(e)) and not e.get("doi")


def note_for(r, e, rec_name, routes, dup_note=None, extra_notes=()):
    k, src = r["key"], r["src"]
    label, rest = l_label(e.get("note") or "")
    rest = SCRATCH_SENT.sub("", rest).strip()
    pre = evidence_prefix(label, src)
    if r.get("claim"):
        route = (f"Crossref API /works record of the DOI that {src}'s report names for this work, accepted with the "
                 f"first page standing in for the title the claim does not state ({r['claim']['verdict']}), cached as "
                 f"docs/agent\\_reports/crossref\\_cache/{rec_name}")
    elif arxiv_only(e):
        route = (f"arXiv OAI-PMH records (formats arXiv and arXivRaw) of {arxiv_id(e)}, cached as "
                 f"docs/agent\\_reports/crossref\\_cache/{k}.oai-arxiv.xml and {k}.oai-arxivraw.xml; the arXiv "
                 "query API answered HTTP 406")
    elif e.etype == "phdthesis":
        route = (f"JaLC API record of the doi field (NDL registration; Crossref /works 404), cached as "
                 f"docs/agent\\_reports/crossref\\_cache/{k}.jalc.json, plus the CiNii Research record "
                 f"{cinii_msg(k)['_crid'].replace('.json', '')} (NDL data), cached as {k}.cinii.json")
    elif rec_name and rec_name.endswith(".json") and r["records"]["main"][0] == "JaLC":
        route = (f"JaLC API record of the doi field (Crossref /works 404, doi.org/ra: JaLC), cached as "
                 f"docs/agent\\_reports/crossref\\_cache/{k}.jalc.json")
    elif rec_name:
        route = f"Crossref API /works record of the doi field, cached as docs/agent\\_reports/crossref\\_cache/{rec_name}"
        if arxiv_id(e):
            route += f", plus the arXiv OAI-PMH records of {arxiv_id(e)} ({k}.oai-arxiv.xml)"
    else:
        x = (routes.get("extra") or {}).get(k) or {}
        route = (f"title page of the manual PDF {x.get('pdf')} (HTTP 200; page-1 text cached as "
                 f"docs/agent\\_reports/crossref\\_cache/{k}.titlepage.txt, the PDF itself not committed)")
    ev = " + ".join(pre + [f"METADATA\\_VERIFIED (route: {route}; B4, {DATE})"])
    counted = r["counted"]
    if counted:
        chk = "B4 MISMATCHES (proposal -> record; the record value is used unless stated): " + "; ".join(
            f"{m['field']}: '{m['proposal']}' -> '{m['record']}' [{m['source']}]"
            + (" (proposal kept: record artefact)" if m.get("resolution", "").startswith("proposal kept") else "")
            for m in counted) + "."
    else:
        chk = ("B4: every compared field (" + ", ".join(sorted({c.split('(')[0] for c in r['checked']}))
               + ") agrees with the record.")
    fmt = ""
    if r["format"]:
        fmt = " Formatting of the proposal fixed by rendering from the record: " + "; ".join(
            sorted(set(r["format"]))) + "."
    sets = (routes.get("set") or {}).get(k) or {}
    setn = ""
    if sets:
        setn = " Fields set rather than copied: " + "; ".join(f"{a} = '{b}'" for a, b in sets.items()) + \
               " (reason in tools/bib/b4\\_routes.yaml)."
    info = " ".join(s_ for s_ in extra_notes if s_)
    body = (f"evidence: {ev}; label before B4 ({src} proposal): {label}; provenance: proposed by "
            f"docs/agent\\_reports/{REPORT_OF[src]} (entry {k} of {BIBFILE_OF[src]}); bibliographic fields copied "
            f"from the record by tools/bib/b4\\_check.py. {chk}{fmt}{setn}"
            + (f" {info}" if info else "")
            + (f" {src} note (verbatim apart from LaTeX encoding; not re-checked in B4): {rest}" if rest else "")
            + (f" {dup_note}" if dup_note else ""))
    return latex_safe_note(body)


def latex_safe_note(t):
    """Escape a note for BibTeX. Dashes, quotes, x and +- are ASCII-fied; CJK and kana (Japanese titles
    and names quoted from JaLC/CiNii) stay UTF-8; other non-ASCII characters are LaTeX-encoded where
    possible, else written as [U+XXXX]."""
    import unicodedata
    t = t.replace("–", "--").replace("—", "---").replace("’", "'").replace("‘", "'")
    t = t.replace("“", "``").replace("”", "''").replace("×", "x").replace("±", "+-")
    out = []
    for ch in t:
        if ord(ch) < 128 or unicodedata.name(ch, "").startswith(
                ("CJK", "HIRAGANA", "KATAKANA", "FULLWIDTH", "IDEOGRAPHIC")):
            out.append(ch)
            continue
        enc, bad = bt.unicode_to_latex(ch)
        out.append(enc if not bad else f"[U+{ord(ch):04X}]")
    t = "".join(out)
    t = re.sub(r"(?<!\\)([%#&])", r"\\\1", t)
    t = re.sub(r"(?<![\\$])_", r"\\_", t)
    return t


# ======================================================================= merge
def entry_text(etype, key, fields):
    base = cc.ORDER[:-1]
    base = base[:base.index("booktitle") + 1] + ["school", "type"] + base[base.index("booktitle") + 1:]
    rank = {n: i for i, n in enumerate(base + ["note"])}
    items = sorted(fields.items(), key=lambda kv: rank.get(kv[0], len(rank) - 1.5))
    width = max(len(n) for n, _ in items)
    body = ",\n".join(f"  {n.ljust(width)} = {{{v}}}" for n, v in items)
    return f"@{etype}{{{key},\n{body}\n}}"


def auto_notes(r, routes):
    out = [str(x) for x in ((routes.get("notes") or {}).get(r["key"]) or [])]
    k = r["key"]
    if arxiv_id_of(r):
        am = arxiv_msg(k)
        out.append("arXiv record: versions " + ", ".join(f"{v} {d}" for v, d in am["_versions"])
                   + f"; categories {am['_categories']}"
                   + (f"; journal-ref '{am['_journal_ref']}'" if am["_journal_ref"] else "")
                   + (f"; DOI {am['_doi']}" if am["_doi"] else "") + ".")
    return out


def arxiv_id_of(r):
    return r.get("eprint")


def build_merge(routes, props, base_text, results):
    ent = {(src, e.key): e for src, e in props}
    by_key = {r["key"]: r for r in results}
    blocks = {"L6": [], "L7": []}
    merged = []
    dup_notes = {}
    keep = routes.get("keep_on_duplicate") or {}
    for r in results:
        if r["verdict"] == "DUPLICATE" and keep.get(r["key"]):
            e = ent[(r["src"], r["key"])]
            lab, rest = l_label(e.get("note") or "")
            dup_notes[keep[r["key"]]] = (f"B4 DUPLICATE MERGED HERE: {r['src']} proposed the same DOI as {r['key']}; "
                                         f"its label was '{lab}' and its note reads (verbatim, not re-checked in B4): {rest}")
    for r in results:
        e = ent[(r["src"], r["key"])]
        if not r["verdict"].startswith("VERIFIED"):
            continue
        etype, f, rec_name = render(r, e, routes)
        f["note"] = note_for(r, e, rec_name, routes, extra_notes=auto_notes(r, routes),
                             dup_note=dup_notes.get(r["key"]))
        blocks[r["src"]].append(entry_text(etype, r["key"], f))
        merged.append(r["key"])
    text = base_text
    tk = by_key.get("TAKEGUCHI1990")
    if tk and tk["verdict"] == "CORRECTION-CONFIRMED":
        text, blk = takeguchi_block(text, tk, ent[("L7", "TAKEGUCHI1990")])
        blocks["L7"].append(blk)
        merged.append("TAKEGUCHI1990 (corrected)")
    block = (SECTION + "\n%% L6 (docs/agent_reports/L6_new_refs.bib; report L6_sourced_si_parameters.md)\n\n"
             + "\n\n".join(blocks["L6"])
             + "\n\n%% L7 (docs/agent_reports/L7_new_refs.bib; report L7_surface_realism.md)\n\n"
             + "\n\n".join(blocks["L7"]))
    m = re.search(r"\n\n%% =+\n%% PART 5\n", text)
    text = text[:m.start()] + "\n\n" + block + text[m.start():]
    text = text.replace(HEADER_ANCHOR, HEADER_ANCHOR + HEADER_B4, 1)
    return text, merged


HEADER_ANCHOR = "%% about blocked hosts describe B2's conditions, not the current ones.\n"
HEADER_B4 = """%%
%% B4 UPDATE (2026-09-23): the proposals of L6 and L7 (docs/agent_reports/
%% L6_new_refs.bib, L7_new_refs.bib) were checked field by field against
%% their Crossref, JaLC, arXiv (OAI-PMH), CiNii/NDL or publisher records by
%% tools/bib/b4_check.py (routes and declared decisions in
%% tools/bib/b4_routes.yaml; log docs/agent_reports/B4_verification_log.md;
%% per-entry table docs/agent_reports/B4_results.tsv) and merged under 4n
%% with the bibliographic fields copied from the record (the few values set
%% otherwise are named in the entry's note). Every doi in 4n is the DOI of
%% the cached Crossref or JaLC record it was checked against; none was typed.
%% Reading labels (SECTION_READ, +ABSTRACT) in 4n are those of L6/L7, NOT
%% re-checked by B4. [TAKEGUCHI1990] was corrected from the CiNii/NDL record
%% and moved up from the UNVERIFIED section (its doi by linked records).
%% ENCODING: two thesis records in 4n ([OSAKABE1995THESIS],
%% [TAKEGUCHI1993THESIS]) have only a Japanese title in every record, so
%% their title (and some notes in 4n) are UTF-8; the file is read as UTF-8.
"""


def takeguchi_block(text, r, e):
    base = bt.parse(text)
    old = next(b for b in base if b.key == "TAKEGUCHI1990")
    start = text.rfind("\n\n", 0, old.start)
    text = text[:start] + text[old.end:]
    cm, crm = cinii_msg("TAKEGUCHI1990"), crossref_msg("TAKEGUCHI1990.json")
    loc, url = oup_locator(crm)
    a, b = cc.cr_pages(cm)
    f = {"author": old.get("author"), "title": old.get("title"), "journal": old.get("journal"),
         "volume": cm["volume"], "number": cm["issue"], "pages": f"{a}--{b}", "year": old.get("year"),
         "doi": crm["DOI"]}
    oldvals = "; ".join(f"{n} = '{v}'" for n, v in r["takeguchi"]["old"].items())
    f["note"] = latex_safe_note(
        "evidence: METADATA\\_VERIFIED (route: CiNii Research record "
        f"{cm['_crid'].replace('.json', '')} (NDL article index, NDL bib 3675815, NAID 40005328351), cached as "
        "docs/agent\\_reports/crossref\\_cache/TAKEGUCHI1990.cinii.json, for authors, journal, volume, issue, pages "
        "and year; Crossref API /works record of the doi, cached as docs/agent\\_reports/crossref\\_cache/"
        f"TAKEGUCHI1990.json, for title, journal and date; B4, {DATE}); label before B4: UNVERIFIED (B3 pass 2: fails "
        "the strict five-field rule); provenance: proposed by docs/agent\\_reports/L4\\_citation\\_search.md section "
        "6.2; correction proposed by docs/agent\\_reports/L7\\_surface\\_realism.md section 3.2 row J-i (entry "
        "TAKEGUCHI1990 of L7\\_new\\_refs.bib). B4 CORRECTION (moved from the UNVERIFIED section): old values "
        f"{oldvals}; no volume, number, pages or doi. New: volume = '{f['volume']}', number = '{f['number']}', "
        f"pages = '{f['pages']}' from the CiNii/NDL record (which prints the first page as 'p269' and the byline "
        "'Masaki Takeguchi; Ken Harada; Ryuichi Shimizu', matching the author field; its title lacks the space in "
        "'(110)Surface'); doi = '" + crm["DOI"] + "' from Crossref. The Crossref record carries NO authors, volume "
        "or pages (published-online 1990-08), so the strict five-field rule still cannot be met by Crossref alone; "
        "the DOI is paired with 39(4) 269 by the publisher's own deposited resource URL in that Crossref record, "
        f"{url}, which encodes volume {loc[0]}, issue {loc[1]}, first page {loc[2]} (route 'linked records', "
        "flagged for the orchestrator: to revert, drop the doi field). The OUP landing page itself answered HTTP "
        "403 to B4 and was not read. Relevance: a 1990 Journal of Electron Microscopy report of reflection electron holography of "
        "GaAs(110) (L4, abstract level); body UNVERIFIED (closed).")
    return text, entry_text("article", "TAKEGUCHI1990", f)


def cmd_merge(args):
    routes, props, base_text, results, near = evaluate()
    text, merged = build_merge(routes, props, base_text, results)
    errs, warns, stats = bt.validate(text)
    if errs:
        print("NOT WRITTEN; validation errors:", errs)
        return 1
    BIB.write_text(text)
    print(f"merged {len(merged)} entries into {BIB.relative_to(ROOT)}: {stats}")
    return 0


def cmd_validate(args):
    return cc.cmd_validate(args)


# ======================================================================= report
def label_after(r):
    if r["verdict"].startswith("VERIFIED") or r["verdict"] == "CORRECTION-CONFIRMED":
        return "METADATA_VERIFIED (B4)"
    return "-"


def cmd_report(args):
    routes, props, base_text, results, near = evaluate()
    cols = ["key", "source", "entry_type", "doi", "eprint", "routes_http", "fields_checked", "mismatches",
            "format_fixes", "duplicate_of", "verdict", "action", "label_after"]
    lines = ["\t".join(cols)]
    clean = lambda x: str(x).replace("\t", " ").replace("\n", " ")
    for r in results:
        mm = "; ".join(f"{m['field']}: '{m['proposal']}' vs '{m['record']}' [{m['source']}; {m['kind']}; "
                       f"{m['resolution']}]" for m in r["counted"]) or "none"
        silent = [m for m in r["mism"] if m["kind"] in NONCOUNT]
        if silent:
            mm += " | not counted: " + "; ".join(f"{m['field']} ({m['kind']}, {m['source']})" for m in silent)
        row = [r["key"], r["src"], r["etype"], r["doi"], r["eprint"],
               " | ".join(r["routes"]),
               ",".join(r["checked"]), mm, "; ".join(r["format"]) or "none",
               (f"{r['dup'][0]}:{r['dup'][1]} ({r['dup'][2]})" if r["dup"] else "none"),
               r["verdict"], r["action"], label_after(r)]
        lines.append("\t".join(clean(x) for x in row))
    TSV.write_text("\n".join(lines) + "\n")
    # ---------------- counts
    n = len(results)
    ver = [r for r in results if r["verdict"] == "VERIFIED"]
    cor = [r for r in results if r["verdict"] in ("VERIFIED-CORRECTED", "CORRECTION-CONFIRMED")]
    dup = [r for r in results if r["verdict"] == "DUPLICATE"]
    unv = [r for r in results if r["verdict"].startswith("UNVERIFIED") or r["verdict"] == "CORRECTION-NOT-CONFIRMED"]
    mism = [(r["key"], m) for r in results for m in r["counted"]]
    fmt = [r for r in results if r["format"]]
    text_now = BIB.read_text()
    merged_keys = [r["key"] for r in results if r["verdict"].startswith("VERIFIED") or r["verdict"] == "CORRECTION-CONFIRMED"]
    now = {e.key: e for e in bt.parse(text_now)}
    in_bib = [k for k in merged_keys if k in now and now[k].section == "verified" and "B4" in (now[k].get("note") or "")]
    errs, warns, stats = bt.validate(text_now)
    bad = cc.check_dois_backed(now)
    sets = routes.get("set") or {}
    c = {"proposals checked": n, "L6": sum(r["src"] == "L6" for r in results), "L7": sum(r["src"] == "L7" for r in results),
         "verified (every field agrees, or differs only by a record artefact)": len(ver),
         "verified after correction (incl. the TAKEGUCHI1990 correction)": len(cor),
         "field mismatches (counted)": len(mism), "entries with mismatches": len({k for k, _ in mism}),
         "entries whose proposal had formatting defects (fixed by rendering from the record)": len(fmt),
         "entries with a value set rather than copied (b4_routes.yaml)": len(sets),
         "unverified": len(unv), "duplicates (not merged)": len(dup),
         "merged into references.bib (verified section)": len(in_bib),
         "references.bib entries after merge": stats.get("entries"),
         "references.bib verified / unverified section": f"{stats.get('verified_section')} / {stats.get('unverified_section')}",
         "validation errors": len(errs), "doi fields not backed by a cached record": len(bad)}
    L = [GEN_BEGIN, "", "### Counts (generated)", "", "| quantity | value |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in c.items()]
    L += ["", "### Every counted mismatch, with the record's value (generated)", "",
          "| key | field | proposal | record | record source | resolution |", "|---|---|---|---|---|---|"]
    for k, m in mism:
        L.append(f"| {k} | {md(m['field'])} | {md(m['proposal'])} | {md(m['record'])} | {md(m['source'])} | {md(m['resolution'])} |")
    L += ["", "Differences not counted as mismatches (the record is silent on the field, or white space only):", ""]
    for r in results:
        for m in r["mism"]:
            if m["kind"] in NONCOUNT:
                L.append(f"* {r['key']}: {m['field']} proposal '{md(m['proposal'])}', {m['source']} record "
                         f"'{md(m['record'])}' ({m['kind']})")
    L += ["", "### Values set rather than copied from the record (generated from tools/bib/b4_routes.yaml)", ""]
    for k, d in sets.items():
        L.append(f"* {k}: " + "; ".join(f"{a} = '{md(b)}'" for a, b in d.items()))
    tk = next((r for r in results if r["key"] == "TAKEGUCHI1990"), None)
    if tk and tk.get("takeguchi"):
        L += ["", "### TAKEGUCHI1990 correction (generated)", "",
              f"Verdict: {tk['verdict']} -- {tk['action']}.", "",
              "Old values: " + "; ".join(f"{a} = '{md(b)}'" for a, b in tk["takeguchi"]["old"].items()) + ".", ""]
        L += [f"* {a}: {md(b)}" for a, b in tk["takeguchi"]["tests"].items()]
    L += ["", "### Duplicates (generated)", ""]
    for r in dup:
        L.append(f"* {r['key']} ({r['src']}): {r['action']}")
    L += ["", "Related items with the same first author and a similar title that are NOT duplicates "
          "(different DOI or different year):", ""]
    for a, b, rr, why in near:
        if rr >= 0.80:
            L.append(f"* {a} ~ [{b}] (title similarity {rr}): {why}")
    L += ["", "### Per-entry results (generated; full rows in B4_results.tsv)", "",
          "| key | src | verdict | records (HTTP) | fields checked | mismatches | formatting fixed |",
          "|---|---|---|---|---|---|---|"]
    for r in results:
        rt = "; ".join(x.split(" http")[0].split(" https")[0] + " " + x.rsplit("-> ", 1)[-1].replace("HTTP ", "")
                       for x in r["routes"])
        L.append(f"| {r['key']} | {r['src']} | {r['verdict']} | {md(rt)} | {len(r['checked'])} | "
                 f"{len(r['counted'])} | {md('; '.join(r['format'])) or '-'} |")
    L += ["", "### Formatting defects of the proposals fixed by rendering from the records (generated)", ""]
    from collections import Counter
    cnt = Counter(re.sub(r": [A-Z][A-Za-z]+$", "", re.sub(r"^\w+: ", "", x)) for r in results for x in set(r["format"]))
    for what, nn in cnt.most_common():
        L.append(f"* {nn} x {what}")
    L += ["", f"Validation of docs/references.bib: {json.dumps(stats)}; errors: {errs or 'none'}; "
          f"doi fields without a cached record carrying the same DOI: {bad or 'none'}", "", GEN_END]
    if LOG.exists():
        old = LOG.read_text()
        a, b = old.find(GEN_BEGIN), old.find(GEN_END)
        new = old[:a] + "\n".join(L) + old[b + len(GEN_END):] if a >= 0 and b >= 0 else old + "\n" + "\n".join(L) + "\n"
    else:
        new = "\n".join(L) + "\n"
    LOG.write_text(new)
    print(json.dumps(c, indent=1))
    return 0


def md(x):
    return str(x).replace("|", "\\|").replace("\n", " ")


# ======================================================================= main
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sp = ap.add_subparsers(dest="cmd", required=True)
    f = sp.add_parser("fetch")
    f.add_argument("keys", nargs="*")
    f.add_argument("--refresh", action="store_true")
    for name in ("report", "merge", "validate"):
        sp.add_parser(name)
    a = ap.parse_args()
    return {"fetch": cmd_fetch, "report": globals().get("cmd_report"), "merge": globals().get("cmd_merge"),
            "validate": globals().get("cmd_validate")}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
